import type { Plugin, TAbstractFile } from 'obsidian'
import { App, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import type { PMSettings, Project, ResolvedProjectConfig, StatusConfig, Task } from '../types'
import { DEFAULT_SETTINGS, makeProject, makeTask } from '../types'
import { today } from '../dates'
import { isTerminalStatus } from '../utils'
import { archiveTask as doArchiveTask, unarchiveTask as doUnarchiveTask } from './ArchiveOps'
import { resolveProjectConfig } from './ProjectConfig'
import { computeSchedule } from './Scheduler'
import {
  findParentId,
  findTaskById,
  indexAddSubtree,
  indexRemoveSubtree,
  indexSetParent,
  rebuildTaskIndex
} from './TaskIndex'
import {
  addTaskToTree,
  cloneTaskSubtree,
  deleteTaskFromTree,
  flattenTasks,
  moveTaskInTree,
  repointDescendantFiles,
  updateTaskInTree
} from './TaskTreeOps'
import { hydrateProjectFromFrontmatter, hydrateTaskFromFile, hydrateTasks } from './YamlHydrator'
import {
  FRONTMATTER_KEY,
  TASK_FRONTMATTER_KEY,
  parseFrontmatter,
  splitCommentsSection,
  stripAutoGeneratedContent
} from './YamlParser'
import {
  buildTaskFrontmatter,
  serializeProject,
  serializeTask,
  taskFilePath,
  TASK_SLUG_MAX_LENGTH
} from './YamlSerializer'
import { ensureFolder, moveTaskAttachmentFolder } from './vaultFs'
import { caseFilePath, projectFileName, projectFolderForProjectPath, taskFolderForProjectPath } from './layout'
import type { ImportNoteOptions, TaskSource } from './TaskSource'

/**
 * 'fm' — only frontmatter changed; body content is unaffected. Save path can
 * use processFrontMatter and skip reading the body.
 * 'full' — body content depends on the change (description edited, file
 * renamed, archived flag flipped, structural relationships moved). Save path
 * rewrites the whole file atomically via vault.process.
 */
type DirtyKind = 'fm' | 'full'

/** Patches that touch any of these require rewriting the body, not just the frontmatter. */
function patchNeedsBodyRewrite(patch: Partial<Task>): boolean {
  // `subtasks` changes the parent's `## Subtasks` list; `comments` the
  // `## Comments` section — both live in the body.
  return (
    patch.description !== undefined ||
    patch.archived !== undefined ||
    patch.subtasks !== undefined ||
    patch.comments !== undefined
  )
}

/** Recover description AND comments from a raw on-disk body (unhydrated tasks). */
function recoverBodyInto(task: Task, rawBody: string): void {
  const { rest, comments } = splitCommentsSection(rawBody)
  task.description = stripAutoGeneratedContent(rest)
  task.comments = comments
}

/** A basename of this exact length that prefixes the title's slug is kept as-is. */
const LEGACY_SLUG_CAP = 40

/**
 * Pick a save path. New tasks get the bare slug; an existing file is left where
 * it is when its name still matches the title, so an unchanged title isn't renamed.
 */
function resolveTaskPath(task: Task, folder: string, previousPath: string | undefined): string {
  const desired = taskFilePath(task.title, folder)
  if (!previousPath) return desired
  const desiredBasename = desired.slice(desired.lastIndexOf('/') + 1).replace(/\.md$/, '')
  const previousFolder = previousPath.slice(0, previousPath.lastIndexOf('/'))
  const previousBasename = previousPath.slice(previousPath.lastIndexOf('/') + 1).replace(/\.md$/, '')
  if (previousFolder !== folder) return desired
  const legacyBasename = `${desiredBasename}-${task.id.slice(0, 8)}`
  if (previousBasename === legacyBasename) return previousPath
  if (previousBasename.length === LEGACY_SLUG_CAP && previousBasename === desiredBasename.slice(0, LEGACY_SLUG_CAP)) {
    return previousPath
  }
  return desired
}

/** Thrown when saving a task would collide with an existing file in the vault. */
export class TaskFileNameConflictError extends Error {
  constructor(public readonly path: string) {
    super(`A note named "${fileNameFromPath(path)}" already exists.`)
    this.name = 'TaskFileNameConflictError'
  }

  get fileName(): string {
    return fileNameFromPath(this.path)
  }
}

function fileNameFromPath(path: string): string {
  return path.slice(path.lastIndexOf('/') + 1).replace(/\.md$/, '')
}

/**
 * Handles all read/write operations against the Obsidian vault.
 *
 * Storage layout (v3 — see layout.ts for the older recognized shapes):
 *   <Name>/<Name>.md                — project metadata (no task data)
 *   <Name>/Tasks/<slug>.md          — one .md per top-level task
 *   <Name>/Tasks/<slug>/<sub>.md    — subtask files nest inside their
 *                                     parent's own folder, recursively
 *
 * The loader is layout-agnostic (it scans all subfolders and rebuilds the tree
 * from frontmatter), so flat legacy vaults keep loading unchanged. The
 * in-memory Project.tasks tree is assembled on load from individual task files
 * and remains unchanged for views.
 */
export class ProjectStore implements TaskSource {
  /** Per-project promise chains to serialize concurrent saves */
  private saveQueues = new Map<string, Promise<void>>()

  /**
   * Task IDs whose .md file needs writing on the next save, with the kind of
   * write required ('fm' for frontmatter-only, 'full' for whole-file rewrite).
   * Tasks with no filePath are always written as 'full'.
   */
  private dirtyTasks = new Map<string, Map<string, DirtyKind>>()

  /**
   * Tasks and projects whose in-memory `description` is known to match disk
   * (either we just wrote it, or we loaded it from the body). Cache-loaded
   * objects start out absent — their description is empty until loadTaskBody /
   * loadProjectBody fills it, or until a 'full' save reads it back inline.
   */
  private hydratedBodies = new WeakSet<Task | Project>()

  /**
   * Projects already loaded this session, keyed by file path. The cached
   * object is the in-memory canonical copy: mutators keep it current, every
   * successful save re-points the entry at the saved object, and external
   * (non-self-write) vault events drop the entry so the next load re-reads.
   */
  private projectCache = new Map<string, Project>()

  /**
   * Paths we've just written, created, or trashed ourselves, timestamped.
   * The view's modify/delete listeners consume markers to skip reloads; the
   * cache invalidation listeners peek at them without consuming.
   * Stale entries (older than the window) are treated as never-marked.
   */
  private selfWrites = new Map<string, number>()
  private static readonly SELF_WRITE_WINDOW_MS = 5000

  constructor(
    private app: App,
    private getSettings: () => PMSettings = () => DEFAULT_SETTINGS
  ) {}

  configFor(project: Project): ResolvedProjectConfig {
    return resolveProjectConfig(project, this.getSettings())
  }

  private statusesFor(project: Project): StatusConfig[] {
    return this.configFor(project).statuses
  }

  // ─── Dirty tracking ───────────────────────────────────────────────────────

  private markDirty(project: Project, taskIds: Iterable<string>, kind: DirtyKind): void {
    let map = this.dirtyTasks.get(project.filePath)
    if (!map) {
      map = new Map()
      this.dirtyTasks.set(project.filePath, map)
    }
    for (const id of taskIds) {
      // Upgrade-only: 'full' wins over 'fm', never the reverse.
      if (map.get(id) === 'full') continue
      map.set(id, kind)
    }
  }

  private markSubtreeDirty(project: Project, taskId: string, kind: DirtyKind): void {
    const task = findTaskById(project, taskId)
    if (!task) return
    this.markDirty(project, [taskId], kind)
    for (const ft of flattenTasks(task.subtasks)) {
      this.markDirty(project, [ft.task.id], kind)
    }
  }

  private markAllDirty(project: Project, kind: DirtyKind): void {
    const ids: string[] = []
    for (const ft of flattenTasks(project.tasks)) ids.push(ft.task.id)
    this.markDirty(project, ids, kind)
  }

  private clearDirty(project: Project): void {
    this.dirtyTasks.delete(project.filePath)
  }

  // ─── Self-write tracking ──────────────────────────────────────────────────

  private markSelfWrite(path: string): void {
    // Created files have no consumer, so sweep expired markers before they pile up.
    if (this.selfWrites.size > 256) {
      const cutoff = Date.now() - ProjectStore.SELF_WRITE_WINDOW_MS
      for (const [p, t] of this.selfWrites) {
        if (t < cutoff) this.selfWrites.delete(p)
      }
    }
    this.selfWrites.set(path, Date.now())
  }

  /** Returns true if we wrote this path recently. Consumes the marker either way. */
  consumeSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    if (ts === undefined) return false
    this.selfWrites.delete(path)
    return Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /** Like consumeSelfWrite, but non-destructive — view listeners still need the marker. */
  private peekSelfWrite(path: string): boolean {
    const ts = this.selfWrites.get(path)
    return ts !== undefined && Date.now() - ts < ProjectStore.SELF_WRITE_WINDOW_MS
  }

  /**
   * Wire vault events that drop cached projects on external changes. Call once
   * from onload, before any view registers listeners — these must run first so
   * a view's reload after an external edit misses the stale cache entry.
   */
  registerCacheInvalidation(plugin: Plugin): void {
    const onChange = (file: TAbstractFile): void => this.invalidateForPath(file.path)
    plugin.registerEvent(this.app.vault.on('create', onChange))
    plugin.registerEvent(this.app.vault.on('modify', onChange))
    plugin.registerEvent(this.app.vault.on('delete', onChange))
    plugin.registerEvent(
      this.app.vault.on('rename', (file, oldPath) => {
        this.invalidateForPath(file.path)
        this.invalidateForPath(oldPath)
      })
    )
  }

  private invalidateForPath(path: string): void {
    if (this.projectCache.size === 0) return
    if (this.peekSelfWrite(path)) return
    for (const key of this.projectCache.keys()) {
      if (path === key || path.startsWith(taskFolderForProjectPath(key) + '/')) {
        this.projectCache.delete(key)
      }
    }
  }

  // ─── Folder helpers ────────────────────────────────────────────────────────

  async ensureFolder(folderPath: string): Promise<void> {
    await ensureFolder(this.app, folderPath)
  }

  /** Get the task subfolder path for a project */
  private projectTaskFolder(project: Project): string {
    return taskFolderForProjectPath(project.filePath)
  }

  /**
   * The folder a task's file belongs in: its parent's own folder (parent file
   * path minus `.md`) for subtasks, the project's task folder for roots, and
   * the flat `Archive` for archived tasks. Falls back to the project folder
   * when the parent has no file yet (its write failed) — the loader is
   * layout-agnostic and the next successful save relocates.
   */
  private folderForTask(project: Project, task: Task): string {
    const base = this.projectTaskFolder(project)
    if (task.archived) return normalizePath(base + '/Archive')
    const parentId = findParentId(project, task.id)
    const parent = parentId ? findTaskById(project, parentId) : null
    return parent?.filePath ? this.taskFolder(parent.filePath) : base
  }

  // ─── Load ──────────────────────────────────────────────────────────────────

  async loadAllProjects(folder: string): Promise<Project[]> {
    if (folder) await this.ensureFolder(folder)
    const files = this.findProjectFiles(folder)
    const loaded = await Promise.all(files.map((f) => this.loadProject(f)))
    const projects = loaded.filter((p): p is Project => p !== null)
    return projects.sort((a, b) => a.title.localeCompare(b.title))
  }

  /**
   * Enumerate candidate project files under the base folder ('' = vault root)
   * across every layout without reading bodies: legacy `<base>/X.md`, v2
   * `<base>/Cases/X.md`, v3 `<base>/<Name>/<Name>.md`. Files the metadataCache
   * already knows are not pm-projects are skipped without a disk read;
   * loadProject re-verifies the frontmatter of the rest.
   */
  private findProjectFiles(base: string): TFile[] {
    const root = this.app.vault.getAbstractFileByPath(normalizePath(base || '/'))
    if (!(root instanceof TFolder)) return []
    const out: TFile[] = []
    const seen = new Set<string>()
    const push = (f: TAbstractFile | null): void => {
      if (!(f instanceof TFile) || f.extension !== 'md' || seen.has(f.path)) return
      const cached = this.app.metadataCache.getFileCache(f)?.frontmatter
      if (cached && cached[FRONTMATTER_KEY] !== true) return
      seen.add(f.path)
      out.push(f)
    }
    for (const child of root.children) {
      if (child instanceof TFile) {
        push(child) // legacy
      } else if (child instanceof TFolder) {
        push(this.app.vault.getAbstractFileByPath(`${child.path}/${child.name}.md`)) // v3
        if (child.name === 'Cases') {
          for (const c of child.children) {
            if (c instanceof TFile) push(c) // v2
          }
        }
      }
    }
    return out
  }

  async loadProject(file: TFile): Promise<Project | null> {
    const cachedProject = this.projectCache.get(file.path)
    if (cachedProject) return cachedProject
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the disk read.
      // Only safe for new-format projects (taskIds in frontmatter, no embedded tasks).
      // For old-format projects we need the body anyway to migrate, so fall back to
      // a real read.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      const cacheUsable =
        cached && cached[FRONTMATTER_KEY] === true && !Array.isArray(cached.tasks) && Array.isArray(cached.taskIds)

      let frontmatter: Record<string, unknown> | null = null
      let body = ''
      let bodyRead = false
      if (cacheUsable) {
        frontmatter = cached
      } else {
        const content = await this.app.vault.cachedRead(file)
        const parsed = parseFrontmatter(content)
        frontmatter = parsed.frontmatter
        body = parsed.body
        bodyRead = true
      }
      if (!frontmatter || frontmatter[FRONTMATTER_KEY] !== true) return null

      const hasEmbeddedTasks = Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0

      const project = hydrateProjectFromFrontmatter(frontmatter, body, file.path, file.basename)
      if (bodyRead) this.hydratedBodies.add(project)

      if (hasEmbeddedTasks) {
        project.tasks = hydrateTasks((frontmatter.tasks as unknown[]) ?? [])
        rebuildTaskIndex(project)
        // Old format: no per-task files on disk yet, so mark everything dirty.
        this.markAllDirty(project, 'full')
      } else {
        const taskFolder = this.projectTaskFolder(project)
        const taskIds = Array.isArray(frontmatter.taskIds) ? (frontmatter.taskIds as string[]) : []
        project.tasks = await this.loadTasksFromFolder(taskFolder, taskIds)
        rebuildTaskIndex(project)
        // Memory matches disk now, drop any stale dirty entries.
        this.clearDirty(project)
      }

      this.projectCache.set(file.path, project)
      return project
    } catch (e) {
      console.error(`[PM] Failed to load project ${file.path}:`, e)
      new Notice(`Casefile: Failed to load "${file.basename}". Check console for details.`)
      return null
    }
  }

  private async loadTasksFromFolder(folderPath: string, topLevelIds: string[]): Promise<Task[]> {
    const folder = this.app.vault.getAbstractFileByPath(folderPath)
    if (!(folder instanceof TFolder)) return []

    const taskMap = new Map<string, Task>()
    const subtaskIdsMap = new Map<string, string[]>()
    const parentIdMap = new Map<string, string>()
    const archivePrefix = normalizePath(folderPath + '/Archive') + '/'

    // Walk the task folder directly (plus Archive). Don't scan the whole vault.
    const files: TFile[] = []
    const collect = (f: TFolder): void => {
      for (const child of f.children) {
        if (child instanceof TFile && child.extension === 'md') files.push(child)
        else if (child instanceof TFolder) collect(child)
      }
    }
    collect(folder)

    const results = await Promise.all(files.map((file) => this.loadTaskFile(file)))
    for (let i = 0; i < files.length; i++) {
      const { task, subtaskIds, parentId } = results[i]
      if (task) {
        if (files[i].path.startsWith(archivePrefix)) {
          task.archived = true
        }
        taskMap.set(task.id, task)
        if (subtaskIds.length) subtaskIdsMap.set(task.id, subtaskIds)
        if (parentId) parentIdMap.set(task.id, parentId)
      }
    }

    for (const [taskId, sids] of subtaskIdsMap) {
      const task = taskMap.get(taskId)
      if (!task) continue
      task.subtasks = []
      for (const sid of sids) {
        const sub = taskMap.get(sid)
        if (sub) task.subtasks.push(sub)
      }
    }

    // Self-healing: re-parent orphaned tasks using parentId from their files
    const childIds = new Set<string>()
    for (const t of taskMap.values()) {
      for (const s of t.subtasks) childIds.add(s.id)
    }
    for (const [taskId, pid] of parentIdMap) {
      if (childIds.has(taskId)) continue // already parented
      const parent = taskMap.get(pid)
      if (!parent) continue
      const task = taskMap.get(taskId)
      if (!task) continue
      parent.subtasks.push(task)
      childIds.add(taskId)
      // Ensure parent's subtaskIds stay in sync
      if (!subtaskIdsMap.has(pid)) subtaskIdsMap.set(pid, [])
      const sids = subtaskIdsMap.get(pid)
      if (sids && !sids.includes(taskId)) sids.push(taskId)
      console.warn(
        `[PM] Self-healed orphan: re-parented task "${task.title}" (${taskId}) under "${parent.title}" (${pid})`
      )
    }

    const result: Task[] = []
    const pushed = new Set<string>()
    for (const id of topLevelIds) {
      if (pushed.has(id)) continue
      const task = taskMap.get(id)
      if (task) {
        result.push(task)
        pushed.add(id)
      }
    }
    for (const task of taskMap.values()) {
      if (pushed.has(task.id)) continue
      if (!childIds.has(task.id)) result.push(task)
    }

    return result
  }

  async loadTaskFile(file: TFile): Promise<{ task: Task | null; subtaskIds: string[]; parentId: string | null }> {
    try {
      // Fast path: pull frontmatter from Obsidian's metadataCache, skip the body
      // read. The description stays empty until loadTaskBody fills it on modal
      // open, or a 'full' save reads it back inline.
      const cached = this.app.metadataCache.getFileCache(file)?.frontmatter
      if (cached && cached[TASK_FRONTMATTER_KEY] === true) {
        return hydrateTaskFromFile(cached, '', file.path)
      }

      const content = await this.app.vault.cachedRead(file)
      const { frontmatter, body } = parseFrontmatter(content)
      if (!frontmatter || frontmatter[TASK_FRONTMATTER_KEY] !== true) {
        return { task: null, subtaskIds: [], parentId: null }
      }

      const result = hydrateTaskFromFile(frontmatter, body, file.path)
      this.hydratedBodies.add(result.task)
      return result
    } catch (e) {
      if (e instanceof Error && e.message.includes('ENOENT')) {
        console.warn(`[PM] Task file no longer exists, skipping: ${file.path}`)
      } else {
        console.error(`[PM] Failed to load task ${file.path}:`, e)
        new Notice(`Casefile: Failed to load task "${file.basename}". Check console for details.`)
      }
      return { task: null, subtaskIds: [], parentId: null }
    }
  }

  /**
   * Read the task's file body and populate its description if not already
   * loaded. Modal callers use this to render the real description in one paint.
   * No-op for tasks whose description is already known to match disk.
   */
  async loadTaskBody(task: Task): Promise<void> {
    if (this.hydratedBodies.has(task)) return
    if (!task.filePath) {
      this.hydratedBodies.add(task)
      return
    }
    const file = this.app.vault.getAbstractFileByPath(task.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(task)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { body } = parseFrontmatter(content)
    recoverBodyInto(task, body)
    this.hydratedBodies.add(task)
  }

  /** Same as loadTaskBody but for the project file's body. */
  async loadProjectBody(project: Project): Promise<void> {
    if (this.hydratedBodies.has(project)) return
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (!(file instanceof TFile)) {
      this.hydratedBodies.add(project)
      return
    }
    const content = await this.app.vault.cachedRead(file)
    const { frontmatter, body } = parseFrontmatter(content)
    const fmDesc = frontmatter?.description
    project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
    this.hydratedBodies.add(project)
  }

  // ─── Save ──────────────────────────────────────────────────────────────────

  async saveProject(project: Project): Promise<void> {
    const key = project.filePath
    const prev = this.saveQueues.get(key) ?? Promise.resolve()
    const next = (async () => {
      await prev
      await this.doSaveProject(project)
    })()
    this.saveQueues.set(
      key,
      (async () => {
        try {
          await next
        } catch {
          // swallow so the next queued save still runs after a failure
        }
      })()
    )
    return next
  }

  private async doSaveProject(project: Project): Promise<void> {
    // Snapshot the dirty map and drop the live entry up front (before any await),
    // so concurrent markDirty calls land in the next save's map, not this one's.
    const dirty = this.dirtyTasks.get(project.filePath) ?? new Map<string, DirtyKind>()
    this.dirtyTasks.delete(project.filePath)

    try {
      project.updatedAt = new Date().toISOString()

      // Issue-key choke point: every creation path (insert, duplicate, subtask
      // reconcile, import) funnels through here as a dirty task, so assigning
      // keys to dirty keyless tasks covers them all with zero per-path code.
      // nextKeySeq persists in the project rewrite below, in the same save.
      if (project.keyPrefix) {
        for (const id of dirty.keys()) {
          const task = findTaskById(project, id)
          if (task && task.key === '') task.key = `${project.keyPrefix}-${project.nextKeySeq++}`
        }
      }

      const taskFolder = this.projectTaskFolder(project)
      await this.ensureFolder(taskFolder)

      await this.saveDirtyTasks(project, taskFolder, dirty)

      const file = this.app.vault.getAbstractFileByPath(project.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(project.filePath)
        // Atomic read-modify-write. The mutator recovers the on-disk description
        // when the in-memory project hasn't been hydrated yet.
        await this.app.vault.process(file, (content) => {
          if (!this.hydratedBodies.has(project)) {
            const { frontmatter, body } = parseFrontmatter(content)
            const fmDesc = frontmatter?.description
            project.description = typeof fmDesc === 'string' ? fmDesc : body.trim()
          }
          return serializeProject(project, this.statusesFor(project))
        })
        this.hydratedBodies.add(project)
      } else {
        const content = serializeProject(project, this.statusesFor(project))
        this.markSelfWrite(project.filePath)
        await this.app.vault.create(project.filePath, content)
        this.hydratedBodies.add(project)
      }
      // The object we just saved is the canonical in-memory copy (it may be a
      // clone of a previously cached project, e.g. from the project modal).
      this.projectCache.set(project.filePath, project)
    } catch (e) {
      // Save failed. Merge the snapshot back so the next save retries.
      for (const [id, kind] of dirty) this.markDirty(project, [id], kind)
      if (e instanceof TaskFileNameConflictError) throw e
      console.error(`[PM] Failed to save project "${project.title}":`, e)
      new Notice(`Casefile: Failed to save "${project.title}". Check console for details.`)
      throw e
    }
  }

  /**
   * Write exactly the dirty tasks, located through the O(1) task index instead
   * of walking the whole tree. A subtask's folder is its parent's file path
   * minus `.md`, so parents must settle (write, maybe rename) before their
   * children's folders resolve — depth levels run in order, and within a level
   * writes target distinct files, so they run concurrently — batched.
   */
  private async saveDirtyTasks(project: Project, folder: string, dirty: Map<string, DirtyKind>): Promise<void> {
    // Safety net: a task that has never been written to disk must get a file
    // even if no mutator marked it.
    for (const [id, entry] of project.taskIndex) {
      if (!entry.task.filePath && !dirty.has(id)) dirty.set(id, 'full')
    }
    if (dirty.size === 0) return

    const byDepth = new Map<number, { task: Task; parentTask: Task | null; kind: DirtyKind }[]>()
    for (const [id, kind] of dirty) {
      const entry = project.taskIndex.get(id)
      if (!entry) continue // deleted after being marked dirty
      let depth = 0
      for (let p = entry.parentId; p; p = project.taskIndex.get(p)?.parentId ?? null) depth++
      const level = byDepth.get(depth) ?? []
      level.push({ task: entry.task, parentTask: entry.parentId ? findTaskById(project, entry.parentId) : null, kind })
      byDepth.set(depth, level)
    }

    const targetPaths = new Set<string>()
    const errors: Error[] = []
    const batchSize = 16
    for (const depth of [...byDepth.keys()].sort((a, b) => a - b)) {
      const jobs: { task: Task; parentTask: Task | null; folder: string; kind: DirtyKind }[] = []
      const folders = new Set<string>()
      for (const j of byDepth.get(depth) ?? []) {
        const jobFolder = this.folderForTask(project, j.task)
        // Two dirty tasks resolving to the same file would race below and surface
        // as a generic create error; detect it up front and keep the typed error.
        const path = normalizePath(resolveTaskPath(j.task, jobFolder, j.task.filePath))
        if (targetPaths.has(path)) throw new TaskFileNameConflictError(path)
        targetPaths.add(path)
        folders.add(jobFolder)
        jobs.push({ ...j, folder: jobFolder })
      }
      for (const f of folders) {
        if (f !== folder) await this.ensureFolder(f)
      }
      for (let i = 0; i < jobs.length; i += batchSize) {
        const results = await Promise.allSettled(
          jobs.slice(i, i + batchSize).map((j) => this.saveTaskFile(j.task, project, j.parentTask, j.folder, j.kind))
        )
        for (const r of results) {
          if (r.status === 'rejected') errors.push(r.reason instanceof Error ? r.reason : new Error(String(r.reason)))
        }
      }
    }
    if (errors.length) {
      if (errors.length === 1 && errors[0] instanceof TaskFileNameConflictError) throw errors[0]
      throw new Error(`Failed to save ${errors.length} task(s): ${errors.map((e) => e.message).join('; ')}`)
    }
  }

  private async saveTaskFile(
    task: Task,
    project: Project,
    parentTask: Task | null,
    folder: string,
    kind: DirtyKind
  ): Promise<void> {
    const previousPath = task.filePath
    const filePath = normalizePath(resolveTaskPath(task, folder, previousPath))
    const renamed = previousPath !== undefined && previousPath !== filePath

    try {
      // Frontmatter-only fast path: leave the body alone entirely.
      if (kind === 'fm' && previousPath && !renamed) {
        const existing = this.app.vault.getAbstractFileByPath(filePath)
        if (existing instanceof TFile) {
          this.markSelfWrite(filePath)
          const next = buildTaskFrontmatter(task, project, parentTask)
          await this.app.fileManager.processFrontMatter(existing, (fm: Record<string, unknown>) => {
            for (const k of Object.keys(fm)) Reflect.deleteProperty(fm, k)
            Object.assign(fm, next)
          })
          return
        }
        // File missing somehow; fall through to recreate it.
      }

      const existing = this.app.vault.getAbstractFileByPath(filePath)
      if (existing instanceof TFile && existing.path !== previousPath) {
        throw new TaskFileNameConflictError(filePath)
      }

      if (existing instanceof TFile) {
        // In-place full rewrite, atomic. Recover description from disk when not hydrated.
        this.markSelfWrite(filePath)
        await this.app.vault.process(existing, (content) => {
          if (!this.hydratedBodies.has(task)) {
            recoverBodyInto(task, parseFrontmatter(content).body)
          }
          return serializeTask(task, project, parentTask, this.statusesFor(project))
        })
      } else {
        // New file or rename target. For a rename of an unhydrated task, read
        // the old file once to recover the description before creating the new one.
        if (!this.hydratedBodies.has(task) && previousPath) {
          const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
          if (oldFile instanceof TFile) {
            const content = await this.app.vault.cachedRead(oldFile)
            recoverBodyInto(task, parseFrontmatter(content).body)
          }
        }
        const content = serializeTask(task, project, parentTask, this.statusesFor(project))
        this.markSelfWrite(filePath)
        await this.app.vault.create(filePath, content)
      }
      task.filePath = filePath
      this.hydratedBodies.add(task)

      if (renamed && previousPath) {
        const oldFile = this.app.vault.getAbstractFileByPath(previousPath)
        if (oldFile instanceof TFile) {
          this.markSelfWrite(previousPath)
          await this.app.fileManager.trashFile(oldFile)
        }
        // Keep the task's own folder (attachments and nested subtask files)
        // with the renamed note.
        this.markSelfWrite(this.taskFolder(previousPath))
        this.markSelfWrite(this.taskFolder(filePath))
        const carried = await moveTaskAttachmentFolder(this.app, previousPath, filePath)
        if (carried) {
          // The folder move physically carried every descendant file — re-point
          // their in-memory paths, or the next save writes duplicates.
          for (const pair of repointDescendantFiles(task, carried.from, carried.to)) {
            this.markSelfWrite(pair.from)
            this.markSelfWrite(pair.to)
          }
        }
      }
    } catch (e) {
      if (!(e instanceof TaskFileNameConflictError)) {
        console.error(`[PM] Failed to save task "${task.title}" (${task.id}):`, e)
      }
      throw e
    }
  }

  /**
   * Pre-flight check: would saving this task (at its current title) collide
   * with another file already in the vault? Returns a typed error callers can
   * surface inline, or null if the save would proceed cleanly.
   */
  findTaskFileConflict(project: Project, task: Task): TaskFileNameConflictError | null {
    const folder = this.folderForTask(project, task)
    const desired = normalizePath(resolveTaskPath(task, folder, task.filePath))
    if (desired === task.filePath) return null
    const existing = this.app.vault.getAbstractFileByPath(desired)
    return existing instanceof TFile ? new TaskFileNameConflictError(desired) : null
  }

  // ─── CRUD shortcuts ────────────────────────────────────────────────────────

  /**
   * The path a new project's file would get, or null when its folder already
   * exists — creating into an existing folder would merge with (or overwrite
   * parts of) unrelated content, so callers must refuse instead.
   */
  newProjectFilePath(folder: string, title: string): string | null {
    const filePath = caseFilePath(folder, title)
    const projectFolder = filePath.slice(0, filePath.lastIndexOf('/'))
    return this.app.vault.getAbstractFileByPath(projectFolder) ? null : filePath
  }

  async createProject(title: string, folder: string): Promise<Project> {
    const filePath = this.newProjectFilePath(folder, title)
    if (!filePath) {
      throw new Error(`A folder named "${projectFileName(title)}" already exists — not creating a project inside it.`)
    }
    const project = makeProject(title, filePath)
    await this.ensureFolder(filePath.slice(0, filePath.lastIndexOf('/')))
    await this.ensureFolder(this.projectTaskFolder(project))
    await this.saveProject(project)
    return project
  }

  async insertTask(project: Project, task: Task, parentId: string | null = null): Promise<void> {
    if (!task.completed && isTerminalStatus(task.status, this.statusesFor(project))) {
      task.completed = today().toString()
    }
    this.hydratedBodies.add(task)
    addTaskToTree(project.tasks, task, parentId)
    indexAddSubtree(project, task, parentId)
    this.markDirty(project, [task.id], 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Convert an arbitrary vault note into a top-level task file in the project's
   * tasks folder. The note body becomes the task description; notes that are
   * already pm-tasks are skipped. The task is picked up on the next project
   * load via the orphan self-heal, matching how the tasks folder is scanned.
   */
  async importNoteAsTask(project: Project, file: TFile, opts: ImportNoteOptions): Promise<'imported' | 'skipped'> {
    const content = await this.app.vault.read(file)
    const { frontmatter, body } = parseFrontmatter(content)
    if (frontmatter?.[TASK_FRONTMATTER_KEY] === true) return 'skipped'

    const task = makeTask({
      title: file.basename,
      description: body,
      status: opts.status,
      priority: opts.priority
    })
    const folder = this.projectTaskFolder(project)
    await this.ensureFolder(folder)
    const newFilePath = taskFilePath(task.title, folder)
    const newContent = serializeTask(task, project, null, this.statusesFor(project))

    if (opts.handling === 'move') {
      await this.app.fileManager.renameFile(file, newFilePath)
      const moved = this.app.vault.getAbstractFileByPath(newFilePath)
      if (moved instanceof TFile) {
        await this.app.vault.process(moved, () => newContent)
      }
    } else {
      await this.app.vault.create(newFilePath, newContent)
    }
    return 'imported'
  }

  /**
   * Persist a converted task forest (e.g. a TaskNotes import) as task files.
   * Each node's description comes from its source note body; 'move' turns the
   * source file into the task file, 'copy' leaves sources untouched. The
   * project file is not rewritten — the next load self-heals top-level order
   * and parenting from the written parentId/subtaskIds.
   */
  async importTaskForest(
    project: Project,
    roots: Task[],
    sources: Map<string, TFile>,
    handling: 'move' | 'copy'
  ): Promise<number> {
    const baseFolder = this.projectTaskFolder(project)
    await this.ensureFolder(baseFolder)
    let imported = 0

    const writeNode = async (task: Task, parent: Task | null): Promise<void> => {
      // Roots land in the project folder, subtasks inside their parent's just
      // written file's own folder; archived nodes go to the flat Archive.
      const folder = task.archived
        ? normalizePath(baseFolder + '/Archive')
        : parent?.filePath
          ? this.taskFolder(parent.filePath)
          : baseFolder
      if (folder !== baseFolder) await this.ensureFolder(folder)
      const source = sources.get(task.id)
      if (source) {
        const { body } = parseFrontmatter(await this.app.vault.read(source))
        task.description = body
      }
      const desired = taskFilePath(task.title, folder)
      const dest = this.uniqueChildPath(folder, desired.slice(desired.lastIndexOf('/') + 1))
      const content = serializeTask(task, project, parent, this.statusesFor(project))
      if (handling === 'move' && source) {
        await this.app.fileManager.renameFile(source, dest)
        const moved = this.app.vault.getAbstractFileByPath(dest)
        if (moved instanceof TFile) {
          await this.app.vault.process(moved, () => content)
        }
      } else {
        await this.app.vault.create(dest, content)
      }
      task.filePath = dest
      imported++
      for (const child of task.subtasks) {
        await writeNode(child, task)
      }
    }

    for (const root of roots) {
      await writeNode(root, null)
    }
    return imported
  }

  async duplicateTask(project: Project, sourceId: string, includeSubtasks: boolean): Promise<Task | null> {
    const source = findTaskById(project, sourceId)
    if (!source) return null
    const copy = cloneTaskSubtree(source, includeSubtasks)
    // The copy lands beside the source in the same folder, where a clone that
    // keeps the source title would write over the original — so only the root
    // copy needs a free "(copy)" title reserved. Cloned descendants keep their
    // titles: they nest inside the copy's own (new) folder, out of the
    // originals' way.
    const parentId = findParentId(project, sourceId)
    const parent = parentId ? findTaskById(project, parentId) : null
    const baseFolder =
      parent?.filePath && !copy.archived ? this.taskFolder(parent.filePath) : this.projectTaskFolder(project)
    const folder = copy.archived ? normalizePath(baseFolder + '/Archive') : baseFolder
    const usedTitles = new Set(flattenTasks(project.tasks).map((f) => f.task.title))
    this.assignCopyName(copy, folder, usedTitles, new Set())
    // Clones don't have a filePath yet; their description in memory is whatever
    // came from the source. We need to write that body verbatim.
    this.hydratedBodies.add(copy)
    for (const ft of flattenTasks(copy.subtasks)) {
      this.hydratedBodies.add(ft.task)
    }
    addTaskToTree(project.tasks, copy, parentId)
    moveTaskInTree(project.tasks, copy.id, sourceId, 'after')
    indexAddSubtree(project, copy, parentId)
    // Copy and every cloned descendant are new files.
    this.markSubtreeDirty(project, copy.id, 'full')
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
    return copy
  }

  private assignCopyName(task: Task, folder: string, usedTitles: Set<string>, claimed: Set<string>): void {
    const base = task.title.replace(/(?: \(copy(?: \d+)?\))+$/, '')
    for (let n = 1; ; n++) {
      const suffix = n === 1 ? ' (copy)' : ` (copy ${n})`
      const room = TASK_SLUG_MAX_LENGTH - suffix.length
      const title = (base.length > room ? base.slice(0, room).trimEnd() : base) + suffix
      const path = normalizePath(taskFilePath(title, folder))
      if (
        !usedTitles.has(title) &&
        !claimed.has(path) &&
        !(this.app.vault.getAbstractFileByPath(path) instanceof TFile)
      ) {
        usedTitles.add(title)
        claimed.add(path)
        task.title = title
        return
      }
    }
  }

  async moveTask(project: Project, taskId: string, newParentId: string | null): Promise<void> {
    const task = findTaskById(project, taskId)
    if (!task) return
    const oldParentId = findParentId(project, taskId)
    deleteTaskFromTree(project.tasks, taskId)
    addTaskToTree(project.tasks, task, newParentId)
    indexSetParent(project, taskId, newParentId)
    // Moved task's parentId is in frontmatter but its body's Parent: link also changes.
    this.markDirty(project, [taskId], 'full')
    // Old and new parents' bodies (Subtasks list) change.
    if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  async moveTasks(project: Project, taskIds: string[], newParentId: string | null): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const oldParentId = findParentId(project, id)
      deleteTaskFromTree(project.tasks, id)
      addTaskToTree(project.tasks, task, newParentId)
      indexSetParent(project, id, newParentId)
      this.markDirty(project, [id], 'full')
      if (oldParentId) this.markDirty(project, [oldParentId], 'full')
    }
    if (newParentId) this.markDirty(project, [newParentId], 'full')
    await this.saveProject(project)
  }

  /**
   * Stamp or clear `completed` based on a status transition. Mutates `patch` so the
   * date lands in the same save as the status change. A patch that changes
   * `completed` away from the task's current value (a manual edit in the modal, or
   * an import) wins and is left untouched; otherwise crossing the
   * complete/incomplete boundary stamps today's date or clears it.
   *
   * The modal saves the whole task as the patch, so `patch.completed` is almost
   * always present and equal to the stored value — comparing against the task,
   * not just checking presence, is what lets auto-stamping fire from the modal.
   */
  private stampCompletion(project: Project, task: Task, patch: Partial<Task>): void {
    if (patch.status === undefined) return
    if (patch.completed !== undefined && patch.completed !== task.completed) return
    const statuses = this.statusesFor(project)
    const wasComplete = isTerminalStatus(task.status, statuses)
    const nowComplete = isTerminalStatus(patch.status, statuses)
    if (nowComplete && !wasComplete) patch.completed = today().toString()
    else if (!nowComplete && wasComplete) patch.completed = ''
  }

  /** Fields whose changes land in the append-only audit log. A const list, not config. */
  private static readonly ACTIVITY_FIELDS = [
    'status',
    'severity',
    'priority',
    'verdict',
    'assignees',
    'due',
    'bucket'
  ] as const

  /**
   * Append audit-log entries for tracked field changes onto the patch, and
   * auto-stamp incident lifecycle timestamps. Runs beside stampCompletion in
   * both update paths, so drag-drop, inline edits and bulk ops are covered.
   * The task editor saves whole-task patches (deep clones), so diffs compare
   * patch values against the live task; a patch that explicitly carries a
   * lifecycle timestamp different from the live one is a manual edit and wins.
   */
  private stampActivity(project: Project, task: Task, patch: Partial<Task>): void {
    const at = new Date().toISOString()
    const entries: Task['activity'] = []
    for (const field of ProjectStore.ACTIVITY_FIELDS) {
      const next = patch[field]
      if (next === undefined) continue
      const prev = task[field]
      const prevStr = Array.isArray(prev) ? prev.join(', ') : String(prev)
      const nextStr = Array.isArray(next) ? next.join(', ') : String(next)
      if (prevStr === nextStr) continue
      entries.push({ at, field, from: prevStr, to: nextStr })
    }

    // IOC list changes: one entry per added/removed value, diffed against the
    // live task like the fields above. Type/note edits on an existing value
    // don't log — the value is the indicator's identity.
    if (patch.iocs !== undefined) {
      const prevVals = new Set(task.iocs.map((i) => i.value))
      const nextVals = new Set(patch.iocs.map((i) => i.value))
      for (const v of nextVals) if (!prevVals.has(v)) entries.push({ at, field: 'iocs', from: '', to: v })
      for (const v of prevVals) if (!nextVals.has(v)) entries.push({ at, field: 'iocs', from: v, to: '' })
    }

    // Incident lifecycle auto-stamps (manual edits in the patch always win).
    const issueType = patch.issueType ?? task.issueType
    if (issueType === 'incident' && patch.status !== undefined && patch.status !== task.status) {
      const manualResponded = patch.respondedAt !== undefined && patch.respondedAt !== task.respondedAt
      if (!manualResponded && !task.respondedAt) patch.respondedAt = at
      const manualResolved = patch.resolvedAt !== undefined && patch.resolvedAt !== task.resolvedAt
      if (!manualResolved && !task.resolvedAt && isTerminalStatus(patch.status, this.statusesFor(project))) {
        patch.resolvedAt = at
      }
    }

    if (entries.length) {
      const base = patch.activity ?? task.activity
      patch.activity = [...base, ...entries]
    }
  }

  /** Append one audit-log entry directly (breach events etc.) and save. */
  async appendActivity(project: Project, taskId: string, entry: Task['activity'][number]): Promise<void> {
    const task = findTaskById(project, taskId)
    if (!task) return
    updateTaskInTree(project.tasks, taskId, { activity: [...task.activity, entry] })
    this.markDirty(project, [taskId], 'fm')
    await this.saveProject(project)
  }

  async updateTask(project: Project, taskId: string, patch: Partial<Task>): Promise<void> {
    const task = findTaskById(project, taskId)
    const oldTitle = task?.title
    if (task) {
      this.stampCompletion(project, task, patch)
      this.stampActivity(project, task, patch)
    }
    // The task editor saves the whole task, so a patch can add, rename, remove,
    // or reorder subtasks. Snapshot the pre-edit subtree to diff against once the
    // tree has the new one.
    const oldSubtree = task && patch.subtasks !== undefined ? flattenTasks(task.subtasks).map((f) => f.task) : []
    updateTaskInTree(project.tasks, taskId, patch)
    const titleChanged = task && patch.title !== undefined && patch.title !== oldTitle
    // Title change renames the file, which forces the rename branch in saveTaskFile
    // (body rewrite). Description/archived/subtasks patches require a body rewrite too.
    const kind: DirtyKind = patchNeedsBodyRewrite(patch) || titleChanged ? 'full' : 'fm'
    this.markDirty(project, [taskId], kind)
    // Patch-set description is the caller's intent; trust it as the new body.
    if (task && patch.description !== undefined) this.hydratedBodies.add(task)
    if (task && titleChanged) {
      // Title change renames the file, which breaks direct children's Parent link.
      for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
    }
    if (task && patch.subtasks !== undefined) {
      // Re-index the saved subtree and create/rename/trash the affected subtask files.
      await this.reconcileSubtasks(project, task, oldSubtree)
    }
    await this.saveProject(project)
  }

  /**
   * After a save that carries a task's whole subtree (the task editor works on a
   * deep clone), make the index and the on-disk files match it: re-point the
   * index at the saved subtree objects, mark new/renamed/restatused subtasks for
   * a write, and trash the files of subtasks removed in the editor. Unchanged
   * subtasks aren't rewritten.
   */
  private async reconcileSubtasks(project: Project, parent: Task, oldSubtree: Task[]): Promise<void> {
    indexAddSubtree(project, parent, findParentId(project, parent.id))

    const old = new Map(oldSubtree.map((t) => [t.id, t]))
    const liveIds = new Set<string>()
    for (const { task } of flattenTasks(parent.subtasks)) {
      liveIds.add(task.id)
      const prev = old.get(task.id)
      if (!prev) {
        // Brand-new subtask: it needs its own file, body included.
        this.hydratedBodies.add(task)
        this.markDirty(project, [task.id], 'full')
      } else if (prev.title !== task.title) {
        this.markDirty(project, [task.id], 'full')
      } else if (
        // Every mutable frontmatter field editable through the parent's subtask
        // panel must be compared here, or the edit is silently dropped.
        prev.status !== task.status ||
        prev.completed !== task.completed ||
        prev.progress !== task.progress ||
        prev.issueType !== task.issueType ||
        prev.bucket !== task.bucket ||
        prev.severity !== task.severity ||
        prev.verdict !== task.verdict
      ) {
        this.markDirty(project, [task.id], 'fm')
      }
    }

    for (const removed of oldSubtree) {
      if (liveIds.has(removed.id)) continue
      project.taskIndex.delete(removed.id)
      // The flat snapshot already lists every descendant, so trash this file only.
      // (Trashing a file also trashes its own folder, so a removed subtask's
      // nested descendants go with it; their later iterations no-op.)
      if (removed.filePath) await this.deleteTaskFiles({ ...removed, subtasks: [] })
    }
  }

  /**
   * Apply a patch to several tasks in one save. `patch` may be a function
   * producing a per-task patch; return null to leave that task untouched.
   */
  async updateTasks(
    project: Project,
    taskIds: string[],
    patch: Partial<Task> | ((task: Task) => Partial<Task> | null)
  ): Promise<void> {
    for (const id of taskIds) {
      const task = findTaskById(project, id)
      if (!task) continue
      const raw = typeof patch === 'function' ? patch(task) : patch
      if (!raw) continue
      // Copy a shared patch object before stamping so one task's completion date
      // doesn't bleed onto the next iteration through the same reference.
      const p = { ...raw }
      this.stampCompletion(project, task, p)
      this.stampActivity(project, task, p)
      const oldTitle = task.title
      updateTaskInTree(project.tasks, id, p)
      const titleChanged = p.title !== undefined && p.title !== oldTitle
      const kind: DirtyKind = patchNeedsBodyRewrite(p) || titleChanged ? 'full' : 'fm'
      this.markDirty(project, [id], kind)
      if (p.description !== undefined) this.hydratedBodies.add(task)
      if (titleChanged) {
        for (const sub of task.subtasks) this.markDirty(project, [sub.id], 'full')
      }
    }
    await this.saveProject(project)
  }

  /**
   * One-time issue-key adoption for a project. Titles carrying an embedded key
   * ("ARGUS-4: Fix things") donate it: the key moves to `task.key`, the prefix
   * is stripped from the title (which renames the file — vault-wide backlinks
   * outside PM-managed files do NOT auto-update; the caller must warn).
   * Keyless tasks get fresh sequential keys in createdAt order. Idempotent:
   * a second run finds no embedded keys and no keyless tasks, and changes
   * nothing. Not on the TaskSource interface — a one-time pm-file concern.
   */
  async adoptIssueKeys(
    project: Project,
    fallbackPrefix?: string
  ): Promise<{ prefix: string; adopted: number; assigned: number; renamedBasenames: string[] } | null> {
    const flat = flattenTasks(project.tasks).map((f) => f.task)
    const embedded = new Map<string, { seq: number; title: string }>()
    const counts = new Map<string, number>()
    for (const t of flat) {
      const m = /^([A-Z][A-Z0-9]+)-(\d+):?\s*/.exec(t.title)
      if (!m) continue
      embedded.set(t.id, { seq: Number(m[2]), title: t.title.slice(m[0].length) || t.title })
      counts.set(m[1], (counts.get(m[1]) ?? 0) + 1)
    }
    const majority = [...counts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0]
    const hadPrefix = !!project.keyPrefix
    const prefix = project.keyPrefix || majority || fallbackPrefix?.toUpperCase() || ''
    if (!/^[A-Z][A-Z0-9]*$/.test(prefix)) return null

    let adopted = 0
    let assigned = 0
    const renamedBasenames: string[] = []
    const usedSeqs = new Set<number>()
    for (const t of flat) {
      if (t.key) {
        const m = new RegExp(`^${prefix}-(\\d+)$`).exec(t.key)
        if (m) usedSeqs.add(Number(m[1]))
      }
    }

    // Pass 1: adopt embedded keys (first claim on a sequence number wins;
    // duplicates fall through to fresh assignment, title left untouched).
    for (const t of flat) {
      const e = embedded.get(t.id)
      if (!e || t.key || usedSeqs.has(e.seq)) continue
      usedSeqs.add(e.seq)
      t.key = `${prefix}-${e.seq}`
      if (t.filePath) renamedBasenames.push(t.filePath.replace(/^.*\//, ''))
      t.title = e.title
      adopted++
      // Title change renames the file; children's Parent link needs a rewrite.
      this.markDirty(project, [t.id], 'full')
      for (const sub of t.subtasks) this.markDirty(project, [sub.id], 'full')
    }

    // Pass 2: fresh keys for the keyless, oldest first.
    let nextSeq = usedSeqs.size ? Math.max(...usedSeqs) + 1 : 1
    const keyless = flat.filter((t) => !t.key).sort((a, b) => a.createdAt.localeCompare(b.createdAt))
    for (const t of keyless) {
      t.key = `${prefix}-${nextSeq++}`
      assigned++
      this.markDirty(project, [t.id], 'fm')
    }

    project.keyPrefix = prefix
    project.nextKeySeq = nextSeq
    if (adopted || assigned || !hadPrefix) await this.saveProject(project)
    return { prefix, adopted, assigned, renamedBasenames }
  }

  /**
   * One-time migration for flat vaults: move every subtask file that still
   * sits outside its parent's own folder into `<parent file minus .md>/`,
   * keeping its basename. Uses the link-aware rename so wikilinks update, and
   * self-write marking so the vault watcher doesn't thrash. Archived files
   * (and children of archived parents) stay in the flat Archive. Returns the
   * number of files moved; idempotent. Not on the TaskSource interface — a
   * one-time pm-file concern, like adoptIssueKeys.
   */
  async nestSubtaskFiles(project: Project): Promise<number> {
    let moved = 0
    // Pre-order: a parent's own move settles its folder before its children's.
    for (const { task, parentId } of flattenTasks(project.tasks)) {
      if (!parentId || !task.filePath || task.archived) continue
      const parent = findTaskById(project, parentId)
      if (!parent?.filePath || parent.archived) continue
      const folder = this.taskFolder(parent.filePath)
      if (task.filePath.slice(0, task.filePath.lastIndexOf('/')) === folder) continue
      const file = this.app.vault.getAbstractFileByPath(task.filePath)
      if (!(file instanceof TFile)) continue
      const dest = normalizePath(`${folder}/${task.filePath.slice(task.filePath.lastIndexOf('/') + 1)}`)
      if (this.app.vault.getAbstractFileByPath(dest)) continue // occupied — leave it for a manual look
      await this.ensureFolder(folder)
      const oldPath = task.filePath
      this.markSelfWrite(oldPath)
      this.markSelfWrite(dest)
      await this.app.fileManager.renameFile(file, dest)
      task.filePath = dest
      this.markSelfWrite(this.taskFolder(oldPath))
      this.markSelfWrite(this.taskFolder(dest))
      const carried = await moveTaskAttachmentFolder(this.app, oldPath, dest)
      if (carried) {
        // A partially nested vault: this task's own folder carried its nested
        // descendants — re-point them before their own iterations run.
        for (const pair of repointDescendantFiles(task, carried.from, carried.to)) {
          this.markSelfWrite(pair.from)
          this.markSelfWrite(pair.to)
        }
      }
      moved++
    }
    return moved
  }

  /**
   * v3 rename: move the project's folder (and the file inside it) to the new
   * title's name via link-aware renames; the task tree, Archive and attachment
   * folders ride along with the folder. Returns the moved file-path pair,
   * 'occupied' when the target folder already exists (refuse — never rename
   * into unrelated content), or null when nothing needs moving (not a v3
   * project, or the name is unchanged).
   */
  async renameProjectFolder(
    project: Project,
    newTitle: string
  ): Promise<{ from: string; to: string } | 'occupied' | null> {
    const oldFolder = projectFolderForProjectPath(project.filePath)
    if (!oldFolder) return null
    const name = projectFileName(newTitle.trim())
    if (!name) return null
    const parent = oldFolder.slice(0, oldFolder.lastIndexOf('/') + 1) // '' at the vault root
    const newFolder = normalizePath(`${parent}${name}`)
    if (newFolder === oldFolder) return null
    if (this.app.vault.getAbstractFileByPath(newFolder)) return 'occupied'
    const folder = this.app.vault.getAbstractFileByPath(oldFolder)
    if (!(folder instanceof TFolder)) return null

    const oldFile = project.filePath
    const oldName = oldFolder.slice(oldFolder.lastIndexOf('/') + 1)
    const newFile = `${newFolder}/${name}.md`
    const oldTaskFolder = `${oldFolder}/Tasks`
    const newTaskFolder = `${newFolder}/Tasks`
    this.markProjectMove(project, oldFile, newFile, oldTaskFolder, newTaskFolder)
    this.markSelfWrite(oldFolder)
    this.markSelfWrite(newFolder)
    this.markSelfWrite(`${newFolder}/${oldName}.md`)

    await this.app.fileManager.renameFile(folder, newFolder)
    const carried = this.app.vault.getAbstractFileByPath(`${newFolder}/${oldName}.md`)
    if (carried instanceof TFile) {
      await this.app.fileManager.renameFile(carried, newFile)
    }
    this.repointProjectPaths(project, oldFile, newFile, oldTaskFolder, newTaskFolder)
    return { from: oldFile, to: newFile }
  }

  /**
   * One-time v3 migration step: move this project into its own folder directly
   * under `base` ('' = vault root) — `<Name>/<Name>.md` + `<Name>/Tasks/…`.
   * Link-aware renames with self-write marking; nested subtasks, Archive and
   * attachment folders ride along with the folder renames. Returns the moved
   * paths and re-pointed file count, 'occupied' when the target folder is
   * taken, or null when the project already lives at the target (idempotent).
   */
  async moveProjectToOwnFolder(
    project: Project,
    base: string
  ): Promise<{ from: string; to: string; files: number } | 'occupied' | null> {
    const oldFile = project.filePath
    const name = oldFile.slice(oldFile.lastIndexOf('/') + 1).replace(/\.md$/, '')
    const targetFolder = normalizePath(`${base}/${name}`)
    const newFile = `${targetFolder}/${name}.md`
    if (oldFile === newFile) return null
    if (this.app.vault.getAbstractFileByPath(targetFolder)) return 'occupied'
    const file = this.app.vault.getAbstractFileByPath(oldFile)
    if (!(file instanceof TFile)) return null

    const oldTaskFolder = taskFolderForProjectPath(oldFile)
    const newTaskFolder = `${targetFolder}/Tasks`
    this.markProjectMove(project, oldFile, newFile, oldTaskFolder, newTaskFolder)

    const ownFolder = projectFolderForProjectPath(oldFile)
    if (ownFolder) {
      // Already v3-shaped, just not at the base (e.g. still under the old
      // projects folder): one folder rename carries file and task tree together.
      const folder = this.app.vault.getAbstractFileByPath(ownFolder)
      if (!(folder instanceof TFolder)) return null
      this.markSelfWrite(ownFolder)
      this.markSelfWrite(targetFolder)
      await this.app.fileManager.renameFile(folder, targetFolder)
    } else {
      await this.ensureFolder(targetFolder)
      await this.app.fileManager.renameFile(file, newFile)
      const taskFolder = this.app.vault.getAbstractFileByPath(oldTaskFolder)
      if (taskFolder instanceof TFolder) {
        await this.app.fileManager.renameFile(taskFolder, newTaskFolder)
      }
    }
    const files = this.repointProjectPaths(project, oldFile, newFile, oldTaskFolder, newTaskFolder)
    return { from: oldFile, to: newFile, files }
  }

  /** Mark every path a project move will touch as self-written, before the vault ops fire events. */
  private markProjectMove(
    project: Project,
    oldFile: string,
    newFile: string,
    oldTaskFolder: string,
    newTaskFolder: string
  ): void {
    this.markSelfWrite(oldFile)
    this.markSelfWrite(newFile)
    this.markSelfWrite(oldTaskFolder)
    this.markSelfWrite(newTaskFolder)
    for (const { task } of flattenTasks(project.tasks)) {
      if (task.filePath?.startsWith(oldTaskFolder + '/')) {
        this.markSelfWrite(task.filePath)
        this.markSelfWrite(newTaskFolder + task.filePath.slice(oldTaskFolder.length))
      }
    }
  }

  /**
   * After the vault moved a project's file and task tree, make memory match:
   * re-point the project and every task file path, and re-key the path-keyed
   * store maps. Returns the number of files re-pointed (project file included).
   */
  private repointProjectPaths(
    project: Project,
    oldFile: string,
    newFile: string,
    oldTaskFolder: string,
    newTaskFolder: string
  ): number {
    project.filePath = newFile
    let files = 1
    for (const { task } of flattenTasks(project.tasks)) {
      if (task.filePath?.startsWith(oldTaskFolder + '/')) {
        task.filePath = newTaskFolder + task.filePath.slice(oldTaskFolder.length)
        files++
      }
    }
    const dirty = this.dirtyTasks.get(oldFile)
    if (dirty) {
      this.dirtyTasks.delete(oldFile)
      this.dirtyTasks.set(newFile, dirty)
    }
    const queue = this.saveQueues.get(oldFile)
    if (queue) {
      this.saveQueues.delete(oldFile)
      this.saveQueues.set(newFile, queue)
    }
    // The re-pointed object becomes the canonical cached copy under the new
    // key (same doctrine as doSaveProject: a modal clone that gets saved is
    // canonical). The old entry — possibly a stale original — is dropped.
    this.projectCache.delete(oldFile)
    this.projectCache.set(newFile, project)
    return files
  }

  /**
   * Move a task before/after a sibling. Sibling order persists in the parent's
   * subtaskIds (or the project file's taskIds for top-level tasks), so only the
   * parent needs a rewrite.
   */
  async reorderTask(project: Project, taskId: string, targetId: string, position: 'before' | 'after'): Promise<void> {
    if (!moveTaskInTree(project.tasks, taskId, targetId, position)) return
    const parentId = findParentId(project, targetId)
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  async deleteTasks(project: Project, taskIds: string[]): Promise<void> {
    const dirtyParents = new Set<string>()
    for (const id of taskIds) {
      const parentId = findParentId(project, id)
      if (parentId) dirtyParents.add(parentId)
      const task = findTaskById(project, id)
      if (task) {
        await this.deleteTaskFiles(task)
        indexRemoveSubtree(project, task)
      }
      deleteTaskFromTree(project.tasks, id)
    }
    // Parents' bodies (Subtasks list) shrink.
    if (dirtyParents.size) this.markDirty(project, dirtyParents, 'full')
    await this.saveProject(project)
  }

  async archiveTask(project: Project, taskId: string): Promise<void> {
    await doArchiveTask(this.app, project, taskId)
  }

  async unarchiveTask(project: Project, taskId: string): Promise<void> {
    await doUnarchiveTask(this.app, project, taskId)
  }

  async deleteTask(project: Project, taskId: string): Promise<void> {
    const parentId = findParentId(project, taskId)
    const task = findTaskById(project, taskId)
    if (task) {
      await this.deleteTaskFiles(task)
      indexRemoveSubtree(project, task)
    }
    deleteTaskFromTree(project.tasks, taskId)
    // Parent's Subtasks list shrinks.
    if (parentId) this.markDirty(project, [parentId], 'full')
    await this.saveProject(project)
  }

  private async deleteTaskFiles(task: Task): Promise<void> {
    for (const sub of task.subtasks) {
      await this.deleteTaskFiles(sub)
    }
    if (task.filePath) {
      const file = this.app.vault.getAbstractFileByPath(task.filePath)
      if (file instanceof TFile) {
        this.markSelfWrite(task.filePath)
        await this.app.fileManager.trashFile(file)
      }
      // Trash the task's own folder (its attachments) alongside the note.
      const taskDir = this.app.vault.getAbstractFileByPath(this.taskFolder(task.filePath))
      if (taskDir instanceof TFolder) {
        await this.deleteFolderRecursive(taskDir)
      }
    }
  }

  /** A task's own folder, holding its attachments: the task file path minus `.md`. */
  private taskFolder(taskFilePath: string): string {
    return taskFilePath.replace(/\.md$/, '')
  }

  /**
   * Save a pasted or dropped file under the task's own `attachments` folder,
   * keeping it with the task instead of Obsidian's vault-wide default attachment
   * location. Returns the created file so the caller can embed it.
   */
  async saveTaskAttachment(project: Project, task: Task, fileName: string, data: ArrayBuffer): Promise<TFile> {
    const taskPath = task.filePath ?? taskFilePath(task.title, this.projectTaskFolder(project))
    const dir = normalizePath(`${this.taskFolder(taskPath)}/attachments`)
    this.markSelfWrite(this.taskFolder(taskPath))
    this.markSelfWrite(dir)
    await this.ensureFolder(dir)
    const path = this.uniqueChildPath(dir, fileName)
    this.markSelfWrite(path)
    return this.app.vault.createBinary(path, data)
  }

  private uniqueChildPath(folder: string, fileName: string): string {
    const dot = fileName.lastIndexOf('.')
    const base = dot > 0 ? fileName.slice(0, dot) : fileName
    const ext = dot > 0 ? fileName.slice(dot) : ''
    let candidate = normalizePath(`${folder}/${base}${ext}`)
    for (let n = 1; this.app.vault.getAbstractFileByPath(candidate); n++) {
      candidate = normalizePath(`${folder}/${base} ${n}${ext}`)
    }
    return candidate
  }

  async deleteProject(project: Project): Promise<void> {
    // v3: the project's own folder holds everything — trash it whole.
    // Older layouts: task folder + project file live apart, delete both.
    const ownFolder = projectFolderForProjectPath(project.filePath)
    const taskFolder = this.projectTaskFolder(project)
    const folder = this.app.vault.getAbstractFileByPath(ownFolder ?? taskFolder)
    if (folder instanceof TFolder) {
      await this.deleteFolderRecursive(folder)
    }
    const file = this.app.vault.getAbstractFileByPath(project.filePath)
    if (file instanceof TFile) {
      this.markSelfWrite(project.filePath)
      await this.app.fileManager.trashFile(file)
    }
    this.clearDirty(project)
    this.saveQueues.delete(project.filePath)
    this.projectCache.delete(project.filePath)
  }

  private async deleteFolderRecursive(folder: TFolder): Promise<void> {
    for (const child of folder.children.slice()) {
      if (child instanceof TFile) {
        this.markSelfWrite(child.path)
        await this.app.fileManager.trashFile(child)
      } else if (child instanceof TFolder) {
        await this.deleteFolderRecursive(child)
      }
    }
    await this.app.fileManager.trashFile(folder)
  }

  // ─── Scheduling ──────────────────────────────────────────────────────────

  /**
   * Run dependency-based scheduling on the project. Applies computed date
   * patches and saves; returns the number of tasks that were adjusted.
   * A no-op when auto-scheduling is off for this project, so callers can
   * invoke it unconditionally after a change.
   */
  async scheduleAfterChange(project: Project, changedTaskId?: string): Promise<number> {
    const config = this.configFor(project)
    if (!config.autoSchedule) return 0
    const { patches } = computeSchedule(project.tasks, changedTaskId, config.statuses)
    if (patches.length === 0) return 0

    for (const p of patches) {
      updateTaskInTree(project.tasks, p.taskId, { start: p.start, due: p.due })
      // Dates live in frontmatter only.
      this.markDirty(project, [p.taskId], 'fm')
    }
    await this.saveProject(project)
    return patches.length
  }
}
