import { describe, expect, it } from 'vitest'
import {
  appendYaml,
  isOldFormat,
  parseFrontmatter,
  stripAutoGeneratedContent,
  stripGeneratedProjectContent
} from './YamlParser'

describe('parseFrontmatter', () => {
  it('returns null frontmatter when the document has no fences', () => {
    const { frontmatter, body } = parseFrontmatter('just body text')
    expect(frontmatter).toBeNull()
    expect(body).toBe('just body text')
  })

  it('parses a fenced frontmatter block', () => {
    const doc = '---\ntitle: "Hello"\ncount: 3\n---\n\n# Body'
    const { frontmatter, body } = parseFrontmatter(doc)
    expect(frontmatter).toEqual({ title: 'Hello', count: 3 })
    expect(body).toBe('# Body')
  })

  it('returns the full content as body when the closing fence is missing', () => {
    const doc = '---\ntitle: "Hello"\n'
    const { frontmatter, body } = parseFrontmatter(doc)
    expect(frontmatter).toBeNull()
    expect(body).toBe(doc)
  })

  it('falls back to null on malformed yaml', () => {
    const doc = '---\n: : :\n---\nbody'
    const { frontmatter } = parseFrontmatter(doc)
    expect(frontmatter).toBeNull()
  })
})

describe('stripAutoGeneratedContent', () => {
  it('removes Project wiki-link lines', () => {
    expect(stripAutoGeneratedContent('Project: [[my-project|My Project]]')).toBe('')
  })

  it('removes Parent wiki-link lines', () => {
    expect(stripAutoGeneratedContent('Parent: [[parent-slug|Parent]]')).toBe('')
  })

  it('removes a trailing Subtasks section', () => {
    const body = 'Description goes here\n\n## Subtasks\n- [ ] [[sub|Sub]]'
    expect(stripAutoGeneratedContent(body)).toBe('Description goes here')
  })

  it('preserves user content when no auto-generated markers exist', () => {
    expect(stripAutoGeneratedContent('Plain description.')).toBe('Plain description.')
  })

  it('keeps hand-written content below the generated Subtasks list', () => {
    const body = 'Desc.\n\n## Subtasks\n- [ ] [[sub|Sub]]\n- [x] [[done|Done]]\n\n## My notes\nDo not lose me.'
    expect(stripAutoGeneratedContent(body)).toBe('Desc.\n\n## My notes\nDo not lose me.')
  })

  it('keeps stray non-list lines a user wrote under the Subtasks heading', () => {
    const body = '## Subtasks\n- [ ] [[sub|Sub]]\nremember to check the proxy logs'
    expect(stripAutoGeneratedContent(body)).toBe('remember to check the proxy logs')
  })
})

describe('stripGeneratedProjectContent', () => {
  it('removes the generated heading, description, and tasks list, keeping hand-written content', () => {
    const body = [
      '# \u{1F4CB} My Case',
      '',
      'Case description.',
      '',
      '## Tasks',
      '- [ ] [[Alpha|Alpha]]',
      '- [x] [[Beta|Beta]]',
      '',
      '## Investigation notes',
      'Keep me.'
    ].join('\n')
    expect(stripGeneratedProjectContent(body, 'Case description.')).toBe('## Investigation notes\nKeep me.')
  })

  it('returns empty for a fully generated body', () => {
    const body = '# \u{1F4CB} My Case\n\nDesc.\n\n## Tasks\n- [ ] [[A|A]]\n'
    expect(stripGeneratedProjectContent(body, 'Desc.')).toBe('')
  })

  it('does not remove a stale description text that no longer matches', () => {
    // The caller passes the file's own frontmatter description; a non-matching
    // value must not eat unrelated body text.
    const body = '# \u{1F4CB} C\n\nHand paragraph.'
    expect(stripGeneratedProjectContent(body, 'Something else entirely.')).toBe('Hand paragraph.')
  })
})

describe('isOldFormat', () => {
  it('is true when tasks is a non-empty array and taskIds is absent', () => {
    expect(isOldFormat({ tasks: [{ id: 'a' }] })).toBe(true)
  })

  it('is false when taskIds is present even if tasks is also set', () => {
    expect(isOldFormat({ tasks: [{ id: 'a' }], taskIds: ['a'] })).toBe(false)
  })

  it('is false when tasks is empty', () => {
    expect(isOldFormat({ tasks: [] })).toBe(false)
  })

  it('is false when tasks is absent', () => {
    expect(isOldFormat({ title: 'Project' })).toBe(false)
  })
})

describe('appendYaml', () => {
  it('serializes primitive types with quoted strings and unquoted numbers/bools', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'hi', n: 2, b: true, nil: null }, 0)
    expect(lines).toEqual(['s: "hi"', 'n: 2', 'b: true', 'nil:'])
  })

  it('escapes quotes, backslashes, and newlines in strings', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'a "b"\n\\c' }, 0)
    expect(lines).toEqual(['s: "a \\"b\\"\\n\\\\c"'])
  })

  it('emits inline arrays for primitive items and empty arrays as []', () => {
    const lines: string[] = []
    appendYaml(lines, { list: ['a', 'b'], empty: [] }, 0)
    expect(lines).toEqual(['list: ["a", "b"]', 'empty: []'])
  })

  it('emits nested blocks for arrays of objects', () => {
    const lines: string[] = []
    appendYaml(
      lines,
      {
        items: [
          { k: 'v1', n: 1 },
          { k: 'v2', n: 2 }
        ]
      },
      0
    )
    expect(lines).toEqual(['items:', '  - k: "v1"', '    n: 1', '  - k: "v2"', '    n: 2'])
  })

  it('indents nested objects by the given amount', () => {
    const lines: string[] = []
    appendYaml(lines, { outer: { inner: 'x' } }, 0)
    expect(lines).toEqual(['outer:', '  inner: "x"'])
  })
})

describe('frontmatter written by other tools', () => {
  it('parses a CRLF note, and leaves a lone \\r inside a value alone', () => {
    const doc = '---\r\npm-task: true\r\nid: "t1"\r\nupdatedAt: "2026-01-01"\r\n---\r\n\r\nreal desc\r\nline two'
    const { frontmatter, body } = parseFrontmatter(doc)
    expect(frontmatter).toEqual({ 'pm-task': true, id: 't1', updatedAt: '2026-01-01' })
    expect(body).toBe('real desc\nline two')
    expect(parseFrontmatter('---\na: "x\ry"\n---\n').frontmatter).toEqual({ a: 'x\ry' })
  })

  it('writes a carriage return escaped, so it never reaches the YAML raw', () => {
    const lines: string[] = []
    appendYaml(lines, { s: 'a\rb' }, 0)
    expect(lines).toEqual(['s: "a\\rb"'])
    expect(parseFrontmatter(`---\n${lines[0]}\n---\n`).frontmatter).toEqual({ s: 'a\rb' })
  })

  it('quotes keys that are not plain words, so they round-trip', () => {
    const fm = {
      'Ticket #': 'INC-42',
      'Ticket: ref': 'r1',
      null: 'n',
      True: 't',
      '@owner': 'me',
      '#tag': 'x',
      nested: { 'a b': 1 },
      rows: [{ 'x:y': 1, '@z': 2 }],
      plainKey: 'kept'
    }
    const lines: string[] = ['---']
    appendYaml(lines, fm, 0)
    lines.push('---')
    expect(parseFrontmatter(lines.join('\n')).frontmatter).toEqual(fm)
    // Owned keys the plugin writes stay byte-identical.
    expect(lines).toContain('plainKey: "kept"')
  })

  it('writes lists holding nulls, nested arrays or mixed items without crashing or reshaping them', () => {
    const fm = {
      tags: [null],
      related: [null, 'x'],
      coords: [
        [1, 2],
        [3, 4]
      ],
      mixed: [{ a: 1 }, 'str'],
      iocs: [{ type: 'ip', value: '1.2.3.4' }]
    }
    const lines: string[] = ['---']
    appendYaml(lines, fm, 0)
    lines.push('---')
    expect(parseFrontmatter(lines.join('\n')).frontmatter).toEqual(fm)
    // A list of plain objects keeps the block form every existing file uses.
    expect(lines).toContain('  - type: "ip"')
  })
})

describe('stripGeneratedProjectContent with a description that repeats', () => {
  it('strips the paragraph, not the heading, when the title contains the description', () => {
    const body = '# \u{1F4CB} Phishing\n\nPhishing\n\n## Tasks\n- [ ] [[A|A]]'
    expect(stripGeneratedProjectContent(body, 'Phishing')).toBe('')
  })

  it('strips a description saved with a trailing newline', () => {
    expect(stripGeneratedProjectContent('# \u{1F4CB} Q\n\nDesc.', 'Desc.\n')).toBe('')
  })

  it('never cuts a short description out of hand-written text', () => {
    const body = '# \u{1F4CB} C\n\nFIRST responder notes.'
    expect(stripGeneratedProjectContent(body, 'IR')).toBe('FIRST responder notes.')
  })
})
