import type {
  ActivityEntry,
  CustomFieldDef,
  Ioc,
  IssueBucket,
  IssueTypeConfig,
  PriorityConfig,
  Project,
  ProjectConfig,
  SavedView,
  StatusConfig,
  Task,
  TaskLink,
  ViewMode
} from '../types'
import { BUCKETS, makeTask } from '../types'
import { splitCommentsSection, stripAutoGeneratedContent } from './YamlParser'
import { KNOWN_TASK_FRONTMATTER_KEYS } from './YamlSerializer'

// Task lives in types.ts, which a concurrent change owns — the optional field
// is added by augmentation instead (recents.ts precedent). Fold into types.ts
// when convenient.
declare module '../types' {
  interface Task {
    /** User-added frontmatter keys (aliases, cssclasses, …) captured at hydrate and re-emitted after the owned keys on save. Absent when the file has none. */
    extraFrontmatter?: Record<string, unknown>
  }
}

const IOC_TYPES = new Set(['ip', 'domain', 'hash', 'url', 'email'])
const LINK_TYPES = new Set(['blocks', 'relates-to', 'duplicates'])
const BUCKET_IDS = new Set(BUCKETS.map((b) => b.id))

function hydrateBucket(raw: unknown): IssueBucket {
  return typeof raw === 'string' && BUCKET_IDS.has(raw as IssueBucket) ? (raw as IssueBucket) : 'none'
}

function hydrateIocs(raw: unknown): Ioc[] {
  if (!Array.isArray(raw)) return []
  const iocs: Ioc[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const i = entry as Record<string, unknown>
    if (typeof i.value !== 'string' || !i.value || typeof i.type !== 'string' || !IOC_TYPES.has(i.type)) continue
    // note is omitted (never undefined) when absent — the YAML emitter writes literal `undefined` otherwise
    iocs.push({
      type: i.type as Ioc['type'],
      value: i.value,
      ...(typeof i.note === 'string' && i.note ? { note: i.note } : {})
    })
  }
  return iocs
}

/** Accept only well-formed entries ({type in the union, taskId string}); drop garbage silently (hydrateIocs precedent). */
function hydrateLinks(raw: unknown): TaskLink[] {
  if (!Array.isArray(raw)) return []
  const links: TaskLink[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const l = entry as Record<string, unknown>
    if (typeof l.type !== 'string' || !LINK_TYPES.has(l.type)) continue
    const taskId = str(l.taskId, '')
    if (!taskId) continue
    links.push({ type: l.type as TaskLink['type'], taskId })
  }
  return links
}

function hydrateActivity(raw: unknown): ActivityEntry[] {
  if (!Array.isArray(raw)) return []
  const entries: ActivityEntry[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const a = entry as Record<string, unknown>
    if (typeof a.at !== 'string' || typeof a.field !== 'string') continue
    entries.push({
      at: a.at,
      field: a.field,
      from: typeof a.from === 'string' ? a.from : '',
      to: typeof a.to === 'string' ? a.to : ''
    })
  }
  return entries
}

// ─── Hydrate ────────────────────────────────────────────────────────────────

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const filter = (v.filter ?? {}) as Record<string, unknown>
      const viewMode = v.viewMode
      const validViewMode: ViewMode | undefined =
        viewMode === 'table' ||
        viewMode === 'gantt' ||
        viewMode === 'kanban' ||
        viewMode === 'backlog' ||
        viewMode === 'reports'
          ? viewMode
          : undefined
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? 'Untitled',
        filter: {
          text: (filter.text as string) ?? '',
          statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
          priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
          severities: Array.isArray(filter.severities) ? filter.severities : [],
          verdicts: Array.isArray(filter.verdicts) ? filter.verdicts : [],
          assignees: Array.isArray(filter.assignees) ? filter.assignees : [],
          tags: Array.isArray(filter.tags) ? filter.tags : [],
          dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
          showArchived: (filter.showArchived as boolean) ?? false
        },
        sortKey: (v.sortKey as string) ?? 'status',
        sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc',
        ...(validViewMode ? { viewMode: validViewMode } : {})
      }
    })
}

/**
 * A known frontmatter field as text. The plugin's own writer quotes every
 * string, but a hand-edited note does not: `title: 4625` (an event id) arrives
 * as a number, and a YAML 1.1 parser reads an unquoted `2024-05-13 09:22:00`
 * as a Date. A cast let those through, and a number title then threw inside
 * every save of its board. Each is coerced to what the analyst wrote, never
 * dropped: an owned key is not captured as an extra, so a discarded value
 * would be deleted from the note on the next save, and a Date left in place
 * would reach appendYaml's object branch and write `key: {}`.
 */
function str(v: unknown, fallback: string): string {
  if (typeof v === 'string') return v
  if (v instanceof Date) return Number.isNaN(v.getTime()) ? fallback : v.toISOString()
  if ((typeof v === 'number' && Number.isFinite(v)) || typeof v === 'boolean') return String(v)
  return fallback
}

/**
 * A colour, only when it is a hex value or a plain colour name. Colours go
 * into CSS `background`, where `url(…)` is valid and fetches as soon as the
 * board or dashboard draws, so a board note from a shared or synced vault could
 * make the plugin call out with no click. The colour pickers only ever write
 * `#rrggbb`, so nothing a user set is lost. Exported for the settings loader.
 */
export function safeColor(v: unknown, fallback: string): string {
  return typeof v === 'string' && /^(?:#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})|[a-z]+)$/i.test(v) ? v : fallback
}

/** A date-only field (start, due, completed): a Date keeps its calendar day, never a time. */
function day(v: unknown): string {
  return v instanceof Date && !Number.isNaN(v.getTime()) ? v.toISOString().slice(0, 10) : str(v, '')
}

/**
 * A list of text values (tags, assignees, ids). Number items keep their
 * digits, anything that is not text is dropped, and a single scalar where a
 * list belongs (`tags: phishing`) becomes a one-item list instead of being
 * deleted on the next save. Scalar tags are split on commas, which is how
 * Obsidian itself reads `tags: phishing, malware`.
 */
export function strList(v: unknown, splitCommas = false): string[] {
  if (Array.isArray(v)) {
    const out: string[] = []
    for (const item of v) {
      const s = typeof item === 'string' || typeof item === 'number' ? str(item, '') : ''
      if (s) out.push(s)
    }
    return out
  }
  const s = str(v, '').trim()
  if (!s) return []
  return splitCommas
    ? s
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean)
    : [s]
}

/** Time logs whose hours read as a number. A string '1.5' is kept as 1.5; an entry without readable hours is dropped, since adding it would concatenate text into the total. */
function hydrateTimeLogs(raw: unknown[]): Task['timeLogs'] {
  const logs: NonNullable<Task['timeLogs']> = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const l = entry as Record<string, unknown>
    const hours = typeof l.hours === 'number' || (typeof l.hours === 'string' && l.hours.trim()) ? Number(l.hours) : NaN
    if (!Number.isFinite(hours)) continue
    logs.push({ ...(l as unknown as NonNullable<Task['timeLogs']>[number]), hours })
  }
  return logs
}

/** Map raw frontmatter fields to a Task, with optional overrides */
export function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  // Absent when empty (flagged/recurrence idiom): the key never round-trips into files.
  const links = hydrateLinks(r.links)
  const id = str(r.id, '')
  return makeTask({
    // A missing id keeps makeTask's fresh one; a note file passes its own
    // stable fallback through `overrides`.
    ...(id ? { id } : {}),
    key: typeof r.key === 'string' ? r.key : '',
    title: str(r.title, 'Untitled'),
    description: str(r.description, ''),
    type: r.type === 'milestone' ? 'milestone' : r.type === 'subtask' ? 'subtask' : 'task',
    issueType: typeof r.issueType === 'string' && r.issueType ? r.issueType : 'task',
    status: str(r.status, 'todo'),
    priority: str(r.priority, 'medium'),
    severity: typeof r.severity === 'string' ? r.severity : '',
    verdict: typeof r.verdict === 'string' ? r.verdict : '',
    // Anything not literally true (absent, 'yes', 1, …) hydrates to false.
    flagged: r.flagged === true,
    bucket: hydrateBucket(r.bucket),
    start: day(r.start),
    due: day(r.due),
    occurredAt: str(r.occurredAt, ''),
    detectedAt: str(r.detectedAt, ''),
    respondedAt: str(r.respondedAt, ''),
    containedAt: str(r.containedAt, ''),
    resolvedAt: str(r.resolvedAt, ''),
    progress: typeof r.progress === 'number' ? r.progress : 0,
    completed: day(r.completed),
    iocs: hydrateIocs(r.iocs),
    ...(links.length ? { links } : {}),
    attack: strList(r.attack),
    activity: hydrateActivity(r.activity),
    // Fresh arrays and objects, never the source's: on the metadataCache fast
    // path `r` is Obsidian's live frontmatter object, so a shared container
    // would let an in-place task mutation corrupt the cache.
    assignees: strList(r.assignees),
    tags: strList(r.tags, true),
    subtasks: [],
    dependencies: strList(r.dependencies),
    recurrence:
      r.recurrence && typeof r.recurrence === 'object'
        ? ({ ...(r.recurrence as Task['recurrence']) } as Task['recurrence'])
        : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs) ? hydrateTimeLogs(r.timeLogs) : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null
        ? { ...(r.customFields as Record<string, unknown>) }
        : {},
    collapsed: r.collapsed === true,
    // createdAt is the SLA anchor for any case with no detection stamp
    // (slaAnchor). A note that does not record it hydrates as '' (unknown),
    // never as the load time: that restarted the response clock on every
    // load, counted an old case as opened this week and after a reports
    // reset, and the first save wrote the invented time to disk.
    createdAt: str(r.createdAt, ''),
    updatedAt: str(r.updatedAt, new Date().toISOString()),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : []
    })
  })
}

/** Hydrate a task from its frontmatter + body (individual .md file) */
export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  // Comments split first — the `## Subtasks`-to-EOF strip must never eat them.
  const { rest, comments } = splitCommentsSection(body)
  // User-added frontmatter keys survive the save round-trip. JSON-cloned: on
  // the metadataCache fast path `frontmatter` is Obsidian's live object.
  const extra: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(frontmatter)) {
    if (!KNOWN_TASK_FRONTMATTER_KEYS.has(k) && v !== undefined) extra[k] = v
  }
  const task = mapRawToTask(frontmatter, {
    // A note with no id falls back to its own path: the same on every load,
    // and never shared by two notes. A fresh random id here would change on
    // every reload, and two id-less notes used to share `undefined`, so the
    // loader kept one and silently dropped the other.
    id: str(frontmatter.id, '') || filePath,
    description: stripAutoGeneratedContent(rest),
    comments,
    filePath,
    ...(Object.keys(extra).length
      ? { extraFrontmatter: JSON.parse(JSON.stringify(extra)) as Record<string, unknown> }
      : {})
  })
  // Id references are coerced like the ids themselves, or a hand-written
  // numeric-id vault would lose its hierarchy on the next save.
  const subtaskIds = strList(frontmatter.subtaskIds)
  const parentId = str(frontmatter.parentId, '') || null
  return { task, subtaskIds, parentId }
}

/** Build a Project object from frontmatter + body (without tasks) */
export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: str(frontmatter.id, basename),
    title: str(frontmatter.title, basename),
    description: str(frontmatter.description, body.trim()),
    color: safeColor(frontmatter.color, '#8b72be'),
    icon: str(frontmatter.icon, '\u{1F4CB}'),
    tasks: [],
    // Copy containers: on the metadataCache fast path `frontmatter` is Obsidian's
    // live object, so sharing these arrays would let an in-place edit corrupt the cache.
    customFields: Array.isArray(frontmatter.customFields) ? [...(frontmatter.customFields as CustomFieldDef[])] : [],
    teamMembers: strList(frontmatter.teamMembers),
    keyPrefix: typeof frontmatter.keyPrefix === 'string' ? frontmatter.keyPrefix : '',
    nextKeySeq: typeof frontmatter.nextKeySeq === 'number' && frontmatter.nextKeySeq >= 1 ? frontmatter.nextKeySeq : 1,
    // Not recorded stays unknown, as on a task.
    createdAt: str(frontmatter.createdAt, ''),
    updatedAt: str(frontmatter.updatedAt, new Date().toISOString()),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
    config: hydrateProjectConfig(frontmatter.config),
    // Only a readable instant is kept. A hand-edited value that does not parse
    // would otherwise reset the reports to a moment nobody chose.
    ...(typeof frontmatter.reportsSince === 'string' && !Number.isNaN(Date.parse(frontmatter.reportsSince))
      ? { reportsSince: frontmatter.reportsSince }
      : {}),
    taskIndex: new Map()
  }
}

/** Read a project's settings overrides, dropping malformed fields. Absent or empty = inherit everything. */
function hydrateProjectConfig(raw: unknown): ProjectConfig | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const config: ProjectConfig = {}
  // Only 'plain' is read. Anything else — absent, misspelt, a number — leaves the
  // key off, and resolveProjectConfig then reads it as a case board. Fail-open is
  // right here: the worst case is a board showing more than it needs, never less.
  if (r.boardType === 'plain') config.boardType = 'plain'
  const statuses = hydrateStatusList(r.statuses)
  if (statuses) config.statuses = statuses
  const priorities = hydratePriorityList(r.priorities)
  if (priorities) config.priorities = priorities
  const issueTypes = hydrateIssueTypeList(r.issueTypes)
  if (issueTypes) config.issueTypes = issueTypes
  if (
    r.defaultView === 'table' ||
    r.defaultView === 'gantt' ||
    r.defaultView === 'kanban' ||
    r.defaultView === 'backlog' ||
    r.defaultView === 'reports'
  ) {
    config.defaultView = r.defaultView
  }
  if (typeof r.autoSchedule === 'boolean') config.autoSchedule = r.autoSchedule
  if (typeof r.kanbanShowSubtasks === 'boolean') config.kanbanShowSubtasks = r.kanbanShowSubtasks
  if (typeof r.kanbanShowDescriptionPreview === 'boolean') {
    config.kanbanShowDescriptionPreview = r.kanbanShowDescriptionPreview
  }
  return Object.keys(config).length ? config : undefined
}

function hydrateStatusList(raw: unknown): StatusConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const statuses: StatusConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const s = entry as Partial<StatusConfig>
    if (typeof s.id !== 'string' || !s.id) continue
    statuses.push({
      id: s.id,
      label: typeof s.label === 'string' ? s.label : s.id,
      color: safeColor(s.color, '#8a94a0'),
      icon: typeof s.icon === 'string' ? s.icon : '',
      complete: s.complete === true,
      ...(typeof s.wipLimit === 'number' && s.wipLimit > 0 ? { wipLimit: s.wipLimit } : {})
    })
  }
  return statuses.length ? statuses : undefined
}

function hydratePriorityList(raw: unknown): PriorityConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const priorities: PriorityConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const p = entry as Partial<PriorityConfig>
    if (typeof p.id !== 'string' || !p.id) continue
    priorities.push({
      id: p.id,
      label: typeof p.label === 'string' ? p.label : p.id,
      color: safeColor(p.color, '#8a94a0'),
      icon: typeof p.icon === 'string' ? p.icon : ''
    })
  }
  return priorities.length ? priorities : undefined
}

function hydrateIssueTypeList(raw: unknown): IssueTypeConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const issueTypes: IssueTypeConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const t = entry as Partial<IssueTypeConfig>
    if (typeof t.id !== 'string' || !t.id) continue
    issueTypes.push({
      id: t.id,
      label: typeof t.label === 'string' ? t.label : t.id,
      color: safeColor(t.color, '#8a94a0'),
      icon: typeof t.icon === 'string' ? t.icon : ''
    })
  }
  return issueTypes.length ? issueTypes : undefined
}
