import { parseYaml } from 'obsidian'

export const FRONTMATTER_KEY = 'pm-project'
export const TASK_FRONTMATTER_KEY = 'pm-task'

// ─── Parse ──────────────────────────────────────────────────────────────────

export function parseFrontmatter(content: string): {
  frontmatter: Record<string, unknown> | null
  body: string
} {
  // A note that went through Windows git (autocrlf) or some sync tools comes
  // back with CRLF endings. Left alone, the frontmatter slice keeps a trailing
  // \r, the YAML parser rejects it, and the board or case silently fails to
  // load. Only the \r\n pair is folded: a lone \r can sit inside a quoted
  // value written by an older save, and folding it would change that value.
  content = content.replace(/\r\n/g, '\n')
  if (!content.startsWith('---')) return { frontmatter: null, body: content }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { frontmatter: null, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).trim()
  try {
    return { frontmatter: parseYaml(raw) as Record<string, unknown>, body }
  } catch {
    return { frontmatter: null, body: content }
  }
}

/** A generated checkbox wiki-link list item, as emitted under `## Subtasks` / `## Tasks`. */
const GENERATED_LIST_ITEM = /^- \[.\] \[\[.*\]\]\s*$/

/**
 * Remove a generated `## <heading>` list (the heading plus its checkbox
 * wiki-link items and surrounding blanks) from `lines`, in place. Anything
 * else — hand-written content below the list included — is left alone.
 */
function spliceGeneratedList(lines: string[], heading: RegExp): void {
  const start = lines.findIndex((l) => heading.test(l))
  if (start === -1) return
  let end = start + 1
  while (end < lines.length && (lines[end].trim() === '' || GENERATED_LIST_ITEM.test(lines[end]))) end++
  let s = start
  while (s > 0 && lines[s - 1].trim() === '') s--
  lines.splice(s, end - s, ...(s > 0 && end < lines.length ? [''] : []))
}

/** Strip auto-generated wiki-link lines from task body so they don't get duplicated on save */
export function stripAutoGeneratedContent(body: string): string {
  let result = body
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '')
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '')
  // Only the generated list is removed — hand-written content after it survives
  // (it becomes part of the description and round-trips stably from then on).
  const lines = result.split('\n')
  spliceGeneratedList(lines, /^## Subtasks\s*$/)
  return lines.join('\n').trim()
}

/**
 * Remove the generated parts of a project note body — the title heading, the
 * stored description (`prevDescription` = the description the last save wrote,
 * i.e. the file's own frontmatter value), and the `## Tasks` list — leaving the
 * hand-written remainder, which the next save re-emits verbatim after the
 * generated sections.
 */
export function stripGeneratedProjectContent(body: string, prevDescription: string): string {
  // The heading goes first. Searching for the description before that found
  // it inside the heading whenever the title contained it ("Phishing" on a
  // board called "Phishing"), so the real paragraph survived as hand content
  // and the note grew one copy of it per save.
  const headless = body.split('\n')
  if (headless[0]?.startsWith('# ')) headless.shift()
  let result = headless.join('\n').trimStart()
  // Trimmed, because the parsed body is trimmed and a description typed with a
  // trailing newline would otherwise never match. Anchored at the start, where
  // the serializer writes it, so a short description cannot cut a substring
  // out of hand-written text below.
  const desc = prevDescription.trim()
  if (desc && result.startsWith(desc)) result = result.slice(desc.length)
  const lines = result.split('\n')
  spliceGeneratedList(lines, /^## Tasks\s*$/)
  return lines.join('\n').trim()
}

export interface ParsedComment {
  /** 'YYYY-MM-DD HH:mm', or '' for a foreign line preserved verbatim. */
  at: string
  text: string
}

const COMMENT_HEAD = /^> \*\*(\d{4}-\d{2}-\d{2} \d{2}:\d{2})\*\* — (.*)$/
const COMMENTS_HEADING = /^## Comments\s*$/

/**
 * Split the task note's `## Comments` section out of the body. The section
 * runs from the `## Comments` heading to the next `## ` heading, the
 * Parent/Project link line, or EOF. Entries are `> **YYYY-MM-DD HH:mm** — text`
 * blockquotes (continuation `> ` lines joined with newlines). Unrecognized
 * non-blank lines inside the section are preserved verbatim as entries with
 * an empty timestamp — hand-edits are kept, normalized to the entry shape on
 * the next full rewrite (documented limitation).
 *
 * Call this BEFORE stripAutoGeneratedContent: our serializer emits the
 * section ahead of the Parent/Project link, but the `## Subtasks`-to-EOF
 * strip must never get the chance to eat a hand-moved comments section.
 */
export function splitCommentsSection(body: string): { rest: string; comments: ParsedComment[] } {
  const lines = body.split('\n')
  // The LAST heading: the serializer writes the description above the
  // journal, and a description is often pasted alert text. Taking the first
  // one let a pasted `## Comments` line take the journal over, with whatever
  // back-dated entries the paste carried. A reverse loop, not findLastIndex,
  // which is not in lib ES2022.
  let start = -1
  for (let i = lines.length - 1; i >= 0 && start === -1; i--) {
    if (COMMENTS_HEADING.test(lines[i])) start = i
  }
  if (start === -1) return { rest: body, comments: [] }
  let end = lines.length
  for (let i = start + 1; i < lines.length; i++) {
    const l = lines[i]
    if (l.startsWith('## ') || l.startsWith('Project: [[') || l.startsWith('Parent: [[')) {
      end = i
      break
    }
  }

  const comments: ParsedComment[] = []
  let current: ParsedComment | null = null
  for (let i = start + 1; i < end; i++) {
    const line = lines[i]
    // A stamp-shaped line inside an open entry is part of that entry: the
    // serializer always closes an entry with a blank line, so a text line
    // reading "**2020-01-01 09:00** — closed" is never split off as an entry
    // back-dated to whatever the text says.
    const head: RegExpExecArray | null = current ? null : COMMENT_HEAD.exec(line)
    if (head) {
      current = { at: head[1], text: head[2] }
    } else if (current && /^> ?/.test(line)) {
      current.text += '\n' + line.replace(/^> ?/, '')
    } else if (line.trim() !== '') {
      if (current) {
        comments.push(current)
        current = null
      }
      comments.push({ at: '', text: line })
    } else if (current) {
      comments.push(current)
      current = null
    }
  }
  if (current) comments.push(current)

  const rest = [...lines.slice(0, start), ...lines.slice(end)].join('\n')
  return { rest, comments }
}

/**
 * Emit the `## Comments` section lines (empty array when there are no
 * comments). When the description carries its own `## Comments` line, a bare
 * heading is still written after it, so the reader, which takes the last
 * heading, never mistakes the description's for the journal.
 */
export function commentsSectionLines(comments: ParsedComment[] | undefined, description = ''): string[] {
  if (!comments?.length) return description.split('\n').some((l) => COMMENTS_HEADING.test(l)) ? ['## Comments'] : []
  const lines: string[] = ['## Comments', '']
  for (const c of comments) {
    if (!c.at) {
      lines.push(c.text)
      continue
    }
    const [first, ...restLines] = c.text.split('\n')
    lines.push(`> **${c.at}** — ${first}`)
    for (const l of restLines) lines.push(`> ${l}`)
    lines.push('')
  }
  while (lines[lines.length - 1] === '') lines.pop()
  return lines
}

// ─── YAML Writer ────────────────────────────────────────────────────────────

/**
 * A mapping key, double-quoted unless it is a plain word no YAML parser can
 * misread. User-added properties reach the writer through extraFrontmatter, and
 * a legal Obsidian property such as `Ticket: ref`, `Ticket #` or `@owner`
 * written bare breaks the frontmatter, so the case vanishes from its board on
 * the next full save. The reserved words are matched case-insensitively
 * because `True` and `NULL` are read as a boolean and a null too.
 */
function yamlKey(key: string): string {
  return /^[A-Za-z_][\w-]*$/.test(key) && !/^(?:null|true|false)$/i.test(key) ? key : JSON.stringify(key)
}

/** Minimal YAML serializer (handles strings, numbers, booleans, arrays, objects) */
export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent)
  for (const [rawKey, val] of Object.entries(obj)) {
    const key = yamlKey(rawKey)
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`)
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r')
      lines.push(`${pad}${key}: "${escaped}"`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`)
      } else if (val.every((v) => v !== null && typeof v === 'object' && !Array.isArray(v))) {
        // Block form only for a list of plain objects. `typeof null` and an
        // array are 'object' too: an empty `- ` item (null) crashed here and
        // blocked every later save, and nested arrays came back as index-keyed
        // objects. Everything else takes the flow form below, which is valid
        // YAML item by item.
        lines.push(`${pad}${key}:`)
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>)
          if (entries.length === 0) continue
          const [firstKey, firstVal] = entries[0]
          lines.push(`${pad}  - ${yamlKey(firstKey)}: ${JSON.stringify(firstVal)}`)
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${yamlKey(k)}: ${JSON.stringify(v)}`)
          }
        }
      } else {
        const items = val.map((v) => JSON.stringify(v)).join(', ')
        lines.push(`${pad}${key}: [${items}]`)
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val)
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`)
      } else {
        lines.push(`${pad}${key}:`)
        appendYaml(lines, val as Record<string, unknown>, indent + 1)
      }
    }
  }
}

/** Check if a project file uses the old embedded-tasks format */
export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0 && !Array.isArray(frontmatter.taskIds)
}
