import type {
  ActivityEntry,
  CustomFieldDef,
  Ioc,
  IssueBucket,
  IssueTypeConfig,
  PriorityConfig,
  Project,
  ProjectConfig,
  SavedView,
  StatusConfig,
  Task,
  ViewMode
} from '../types'
import { BUCKETS, makeTask } from '../types'
import { splitCommentsSection, stripAutoGeneratedContent } from './YamlParser'

const IOC_TYPES = new Set(['ip', 'domain', 'hash', 'url', 'email'])
const BUCKET_IDS = new Set(BUCKETS.map((b) => b.id))

function hydrateBucket(raw: unknown): IssueBucket {
  return typeof raw === 'string' && BUCKET_IDS.has(raw as IssueBucket) ? (raw as IssueBucket) : 'none'
}

function hydrateIocs(raw: unknown): Ioc[] {
  if (!Array.isArray(raw)) return []
  const iocs: Ioc[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const i = entry as Record<string, unknown>
    if (typeof i.value !== 'string' || !i.value || typeof i.type !== 'string' || !IOC_TYPES.has(i.type)) continue
    // note is omitted (never undefined) when absent — the YAML emitter writes literal `undefined` otherwise
    iocs.push({
      type: i.type as Ioc['type'],
      value: i.value,
      ...(typeof i.note === 'string' && i.note ? { note: i.note } : {})
    })
  }
  return iocs
}

function hydrateActivity(raw: unknown): ActivityEntry[] {
  if (!Array.isArray(raw)) return []
  const entries: ActivityEntry[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const a = entry as Record<string, unknown>
    if (typeof a.at !== 'string' || typeof a.field !== 'string') continue
    entries.push({
      at: a.at,
      field: a.field,
      from: typeof a.from === 'string' ? a.from : '',
      to: typeof a.to === 'string' ? a.to : ''
    })
  }
  return entries
}

// ─── Hydrate ────────────────────────────────────────────────────────────────

export function hydrateSavedViews(raw: unknown[]): SavedView[] {
  if (!Array.isArray(raw)) return []
  return raw
    .filter((r) => r && typeof r === 'object')
    .map((r) => {
      const v = r as Record<string, unknown>
      const filter = (v.filter ?? {}) as Record<string, unknown>
      const viewMode = v.viewMode
      const validViewMode: ViewMode | undefined =
        viewMode === 'table' ||
        viewMode === 'gantt' ||
        viewMode === 'kanban' ||
        viewMode === 'backlog' ||
        viewMode === 'reports'
          ? viewMode
          : undefined
      return {
        id: (v.id as string) ?? '',
        name: (v.name as string) ?? 'Untitled',
        filter: {
          text: (filter.text as string) ?? '',
          statuses: Array.isArray(filter.statuses) ? filter.statuses : [],
          priorities: Array.isArray(filter.priorities) ? filter.priorities : [],
          severities: Array.isArray(filter.severities) ? filter.severities : [],
          verdicts: Array.isArray(filter.verdicts) ? filter.verdicts : [],
          assignees: Array.isArray(filter.assignees) ? filter.assignees : [],
          tags: Array.isArray(filter.tags) ? filter.tags : [],
          dueDateFilter: (filter.dueDateFilter as string as SavedView['filter']['dueDateFilter']) ?? 'any',
          showArchived: (filter.showArchived as boolean) ?? false
        },
        sortKey: (v.sortKey as string) ?? 'status',
        sortDir: (v.sortDir as 'asc' | 'desc') ?? 'asc',
        ...(validViewMode ? { viewMode: validViewMode } : {})
      }
    })
}

/** Map raw frontmatter fields to a Task, with optional overrides */
export function mapRawToTask(r: Record<string, unknown>, overrides?: Partial<Task>): Task {
  return makeTask({
    id: r.id as string,
    key: typeof r.key === 'string' ? r.key : '',
    title: (r.title as string) ?? 'Untitled',
    description: (r.description as string) ?? '',
    type: (r.type as string) === 'milestone' ? 'milestone' : (r.type as string) === 'subtask' ? 'subtask' : 'task',
    issueType: typeof r.issueType === 'string' && r.issueType ? r.issueType : 'task',
    status: (r.status as Task['status']) ?? 'todo',
    priority: (r.priority as Task['priority']) ?? 'medium',
    severity: typeof r.severity === 'string' ? r.severity : '',
    verdict: typeof r.verdict === 'string' ? r.verdict : '',
    bucket: hydrateBucket(r.bucket),
    start: (r.start as string) ?? '',
    due: (r.due as string) ?? '',
    detectedAt: typeof r.detectedAt === 'string' ? r.detectedAt : '',
    respondedAt: typeof r.respondedAt === 'string' ? r.respondedAt : '',
    containedAt: typeof r.containedAt === 'string' ? r.containedAt : '',
    resolvedAt: typeof r.resolvedAt === 'string' ? r.resolvedAt : '',
    progress: typeof r.progress === 'number' ? r.progress : 0,
    completed: (r.completed as string) ?? '',
    iocs: hydrateIocs(r.iocs),
    attack: Array.isArray(r.attack) ? [...(r.attack as string[])].filter((t) => typeof t === 'string') : [],
    activity: hydrateActivity(r.activity),
    // Copy container fields rather than aliasing them. On the metadataCache
    // fast path `r` is Obsidian's live frontmatter object, so a shared array or
    // object would let an in-place task mutation corrupt the cache.
    assignees: Array.isArray(r.assignees) ? [...(r.assignees as string[])] : [],
    tags: Array.isArray(r.tags) ? [...(r.tags as string[])] : [],
    subtasks: [],
    dependencies: Array.isArray(r.dependencies) ? [...(r.dependencies as string[])] : [],
    recurrence:
      r.recurrence && typeof r.recurrence === 'object'
        ? ({ ...(r.recurrence as Task['recurrence']) } as Task['recurrence'])
        : undefined,
    timeEstimate: typeof r.timeEstimate === 'number' ? r.timeEstimate : undefined,
    timeLogs: Array.isArray(r.timeLogs)
      ? (r.timeLogs as { date: string; hours: number; note: string }[]).map((log) => ({ ...log }))
      : undefined,
    customFields:
      typeof r.customFields === 'object' && r.customFields !== null
        ? { ...(r.customFields as Record<string, unknown>) }
        : {},
    collapsed: r.collapsed === true,
    createdAt: (r.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (r.updatedAt as string) ?? new Date().toISOString(),
    ...overrides
  })
}

export function hydrateTasks(raw: unknown[]): Task[] {
  if (!Array.isArray(raw)) return []
  return raw.map((r) => {
    const rec = r as Record<string, unknown>
    return mapRawToTask(rec, {
      subtasks: Array.isArray(rec.subtasks) ? hydrateTasks(rec.subtasks as unknown[]) : []
    })
  })
}

/** Hydrate a task from its frontmatter + body (individual .md file) */
export function hydrateTaskFromFile(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string
): { task: Task; subtaskIds: string[]; parentId: string | null } {
  // Comments split first — the `## Subtasks`-to-EOF strip must never eat them.
  const { rest, comments } = splitCommentsSection(body)
  const task = mapRawToTask(frontmatter, {
    description: stripAutoGeneratedContent(rest),
    comments,
    filePath
  })
  const subtaskIds = Array.isArray(frontmatter.subtaskIds) ? (frontmatter.subtaskIds as string[]) : []
  const parentId = typeof frontmatter.parentId === 'string' && frontmatter.parentId ? frontmatter.parentId : null
  return { task, subtaskIds, parentId }
}

/** Build a Project object from frontmatter + body (without tasks) */
export function hydrateProjectFromFrontmatter(
  frontmatter: Record<string, unknown>,
  body: string,
  filePath: string,
  basename: string
): Project {
  return {
    id: (frontmatter.id as string) ?? basename,
    title: (frontmatter.title as string) ?? basename,
    description: (frontmatter.description as string) ?? body.trim(),
    color: (frontmatter.color as string) ?? '#8b72be',
    icon: (frontmatter.icon as string) ?? '\u{1F4CB}',
    tasks: [],
    // Copy containers: on the metadataCache fast path `frontmatter` is Obsidian's
    // live object, so sharing these arrays would let an in-place edit corrupt the cache.
    customFields: Array.isArray(frontmatter.customFields) ? [...(frontmatter.customFields as CustomFieldDef[])] : [],
    teamMembers: Array.isArray(frontmatter.teamMembers) ? [...(frontmatter.teamMembers as string[])] : [],
    keyPrefix: typeof frontmatter.keyPrefix === 'string' ? frontmatter.keyPrefix : '',
    nextKeySeq: typeof frontmatter.nextKeySeq === 'number' && frontmatter.nextKeySeq >= 1 ? frontmatter.nextKeySeq : 1,
    createdAt: (frontmatter.createdAt as string) ?? new Date().toISOString(),
    updatedAt: (frontmatter.updatedAt as string) ?? new Date().toISOString(),
    filePath,
    savedViews: hydrateSavedViews((frontmatter.savedViews as unknown[]) ?? []),
    config: hydrateProjectConfig(frontmatter.config),
    taskIndex: new Map()
  }
}

/** Read a project's settings overrides, dropping malformed fields. Absent or empty = inherit everything. */
function hydrateProjectConfig(raw: unknown): ProjectConfig | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as Record<string, unknown>
  const config: ProjectConfig = {}
  const statuses = hydrateStatusList(r.statuses)
  if (statuses) config.statuses = statuses
  const priorities = hydratePriorityList(r.priorities)
  if (priorities) config.priorities = priorities
  const issueTypes = hydrateIssueTypeList(r.issueTypes)
  if (issueTypes) config.issueTypes = issueTypes
  if (
    r.defaultView === 'table' ||
    r.defaultView === 'gantt' ||
    r.defaultView === 'kanban' ||
    r.defaultView === 'backlog' ||
    r.defaultView === 'reports'
  ) {
    config.defaultView = r.defaultView
  }
  if (typeof r.autoSchedule === 'boolean') config.autoSchedule = r.autoSchedule
  if (typeof r.kanbanShowSubtasks === 'boolean') config.kanbanShowSubtasks = r.kanbanShowSubtasks
  if (typeof r.kanbanShowDescriptionPreview === 'boolean') {
    config.kanbanShowDescriptionPreview = r.kanbanShowDescriptionPreview
  }
  return Object.keys(config).length ? config : undefined
}

function hydrateStatusList(raw: unknown): StatusConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const statuses: StatusConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const s = entry as Partial<StatusConfig>
    if (typeof s.id !== 'string' || !s.id) continue
    statuses.push({
      id: s.id,
      label: typeof s.label === 'string' ? s.label : s.id,
      color: typeof s.color === 'string' ? s.color : '#8a94a0',
      icon: typeof s.icon === 'string' ? s.icon : '',
      complete: s.complete === true,
      ...(typeof s.wipLimit === 'number' && s.wipLimit > 0 ? { wipLimit: s.wipLimit } : {})
    })
  }
  return statuses.length ? statuses : undefined
}

function hydratePriorityList(raw: unknown): PriorityConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const priorities: PriorityConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const p = entry as Partial<PriorityConfig>
    if (typeof p.id !== 'string' || !p.id) continue
    priorities.push({
      id: p.id,
      label: typeof p.label === 'string' ? p.label : p.id,
      color: typeof p.color === 'string' ? p.color : '#8a94a0',
      icon: typeof p.icon === 'string' ? p.icon : ''
    })
  }
  return priorities.length ? priorities : undefined
}

function hydrateIssueTypeList(raw: unknown): IssueTypeConfig[] | undefined {
  if (!Array.isArray(raw)) return undefined
  const issueTypes: IssueTypeConfig[] = []
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue
    const t = entry as Partial<IssueTypeConfig>
    if (typeof t.id !== 'string' || !t.id) continue
    issueTypes.push({
      id: t.id,
      label: typeof t.label === 'string' ? t.label : t.id,
      color: typeof t.color === 'string' ? t.color : '#8a94a0',
      icon: typeof t.icon === 'string' ? t.icon : ''
    })
  }
  return issueTypes.length ? issueTypes : undefined
}
