import { parseYaml } from 'obsidian'

export const FRONTMATTER_KEY = 'pm-project'
export const TASK_FRONTMATTER_KEY = 'pm-task'

// ─── Parse ──────────────────────────────────────────────────────────────────

export function parseFrontmatter(content: string): {
  frontmatter: Record<string, unknown> | null
  body: string
} {
  if (!content.startsWith('---')) return { frontmatter: null, body: content }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { frontmatter: null, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).trim()
  try {
    return { frontmatter: parseYaml(raw) as Record<string, unknown>, body }
  } catch {
    return { frontmatter: null, body: content }
  }
}

/** Strip auto-generated wiki-link lines from task body so they don't get duplicated on save */
export function stripAutoGeneratedContent(body: string): string {
  let result = body
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '')
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '')
  result = result.replace(/\n## Subtasks[\s\S]*$/, '')
  return result.trim()
}

export interface ParsedComment {
  /** 'YYYY-MM-DD HH:mm', or '' for a foreign line preserved verbatim. */
  at: string
  text: string
}

const COMMENT_HEAD = /^> \*\*(\d{4}-\d{2}-\d{2} \d{2}:\d{2})\*\* — (.*)$/

/**
 * Split the task note's `## Comments` section out of the body. The section
 * runs from the `## Comments` heading to the next `## ` heading, the
 * Parent/Project link line, or EOF. Entries are `> **YYYY-MM-DD HH:mm** — text`
 * blockquotes (continuation `> ` lines joined with newlines). Unrecognized
 * non-blank lines inside the section are preserved verbatim as entries with
 * an empty timestamp — hand-edits are kept, normalized to the entry shape on
 * the next full rewrite (documented limitation).
 *
 * Call this BEFORE stripAutoGeneratedContent: our serializer emits the
 * section ahead of the Parent/Project link, but the `## Subtasks`-to-EOF
 * strip must never get the chance to eat a hand-moved comments section.
 */
export function splitCommentsSection(body: string): { rest: string; comments: ParsedComment[] } {
  const lines = body.split('\n')
  const start = lines.findIndex((l) => /^## Comments\s*$/.test(l))
  if (start === -1) return { rest: body, comments: [] }
  let end = lines.length
  for (let i = start + 1; i < lines.length; i++) {
    const l = lines[i]
    if (l.startsWith('## ') || l.startsWith('Project: [[') || l.startsWith('Parent: [[')) {
      end = i
      break
    }
  }

  const comments: ParsedComment[] = []
  let current: ParsedComment | null = null
  for (let i = start + 1; i < end; i++) {
    const line = lines[i]
    const head = COMMENT_HEAD.exec(line)
    if (head) {
      if (current) comments.push(current)
      current = { at: head[1], text: head[2] }
    } else if (current && /^> ?/.test(line)) {
      current.text += '\n' + line.replace(/^> ?/, '')
    } else if (line.trim() !== '') {
      if (current) {
        comments.push(current)
        current = null
      }
      comments.push({ at: '', text: line })
    } else if (current) {
      comments.push(current)
      current = null
    }
  }
  if (current) comments.push(current)

  const rest = [...lines.slice(0, start), ...lines.slice(end)].join('\n')
  return { rest, comments }
}

/** Emit the `## Comments` section lines (empty array when there are no comments). */
export function commentsSectionLines(comments: ParsedComment[] | undefined): string[] {
  if (!comments?.length) return []
  const lines: string[] = ['## Comments', '']
  for (const c of comments) {
    if (!c.at) {
      lines.push(c.text)
      continue
    }
    const [first, ...restLines] = c.text.split('\n')
    lines.push(`> **${c.at}** — ${first}`)
    for (const l of restLines) lines.push(`> ${l}`)
    lines.push('')
  }
  while (lines[lines.length - 1] === '') lines.pop()
  return lines
}

// ─── YAML Writer ────────────────────────────────────────────────────────────

/** Minimal YAML serializer (handles strings, numbers, booleans, arrays, objects) */
export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent)
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`)
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
      lines.push(`${pad}${key}: "${escaped}"`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`)
      } else if (typeof val[0] === 'object') {
        lines.push(`${pad}${key}:`)
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>)
          if (entries.length === 0) continue
          const [firstKey, firstVal] = entries[0]
          lines.push(`${pad}  - ${firstKey}: ${JSON.stringify(firstVal)}`)
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${k}: ${JSON.stringify(v)}`)
          }
        }
      } else {
        const items = val.map((v) => JSON.stringify(v)).join(', ')
        lines.push(`${pad}${key}: [${items}]`)
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val)
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`)
      } else {
        lines.push(`${pad}${key}:`)
        appendYaml(lines, val as Record<string, unknown>, indent + 1)
      }
    }
  }
}

/** Check if a project file uses the old embedded-tasks format */
export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0 && !Array.isArray(frontmatter.taskIds)
}
