import { MarkdownView, Menu, Plugin, Notice, TFile, TFolder, normalizePath } from 'obsidian'
import { DEFAULT_SETTINGS, type PMSettings, type Project, type Task } from './types'
import { flattenTasks, findTask } from './store/TaskTreeOps'
import { inferIssueKeyPrefix, NestedBoardError, ProjectStore, safeColor } from './store'
import type { TaskSource } from './store'
import { PMSettingTab } from './settings'
import { ProjectView, PM_PROJECT_VIEW_TYPE } from './views/ProjectView'
import { DashboardView, PM_DASHBOARD_VIEW_TYPE } from './views/DashboardView'
import { TaskDetailView, CASEFILE_TASK_DETAIL_VIEW_TYPE } from './views/TaskDetailView'
import { TimelineView, CASEFILE_TIMELINE_VIEW_TYPE } from './views/TimelineView'
import { registerStyleguide } from './views/styleguide/StyleguideView'
import { PMViewRouter } from './views/PMViewRouter'
import {
  openProjectModal,
  openTaskModal,
  openProjectPicker,
  openTaskPicker,
  openCasePicker,
  openImportModal,
  confirmDialog,
  promptText
} from './ui/ModalFactory'
import { AlertIntakeModal } from './modals/AlertIntakeModal'
import { Notifier } from './components/Notifier'
import { openHandoverModal } from './soc/HandoverModal'
import { generateCaseReport } from './soc/caseReport'
import { migrateProjects } from './migration'
import {
  isCasesLayout,
  isProjectFolderLayout,
  parentFolderOf,
  projectFileName,
  taskFolderForProjectPath
} from './store/layout'

import { safeAsync, withUserResponse } from './utils'
import { categoryForTags, normalizeAlertCategories, suggestCategory } from './soc/alertCategory'
import { tickAllSlaChips } from './soc/slaTicker'
import { PHISH_VIEW_TYPE, PhishAnalysisView, openPhishAnalysis } from './views/PhishAnalysisView'
import { openToolbox } from './modals/ToolboxModal'

/**
 * The generated board backlink, as a whole line. Same shape stripAutoGeneratedContent
 * removes on read: every generated link is aliased, `[[basename|alias]]`, and a
 * generated basename never holds '|'. A hand-typed `Project: [[Acme onboarding]]`
 * is not one and stays. ponytail: a hand-typed aliased link is indistinguishable
 * and still goes.
 */
const BOARD_BACKLINK_RE = /^Project: \[\[[^|\n]*\|.*\]\]$\n?/gm

type SecretName = 'virustotal' | 'abuseipdb' | 'abusech'
const SECRET_FIELDS: Record<SecretName, 'virusTotalApiKey' | 'abuseIpdbApiKey' | 'abuseChApiKey'> = {
  virustotal: 'virusTotalApiKey',
  abuseipdb: 'abuseIpdbApiKey',
  abusech: 'abuseChApiKey'
}

/**
 * One step on the undo stack. Only Gantt date drags push these; kanban, table
 * and bulk edits have their own toast Undo. The closures hold the board object
 * itself, which the store keeps as the one live object for that board all
 * session and refreshes in place, so an undo never writes an old copy back.
 */
export interface UndoEntry {
  undo: () => Promise<void>
  redo: () => Promise<void>
  /** What it changes, named in the Notice once undone or redone: 'dates of "Case A" on Queue'. */
  label?: string
}

export default class PMPlugin extends Plugin {
  settings: PMSettings = { ...DEFAULT_SETTINGS }
  store!: TaskSource
  notifier!: Notifier
  router!: PMViewRouter
  undoStack: UndoEntry[] = []
  redoStack: UndoEntry[] = []
  /** Board moves the plugin is making itself; each re-keys its own paths when done. */
  private ownMoves = 0

  pushUndo(entry: UndoEntry): void {
    this.undoStack.push(entry)
    if (this.undoStack.length > 20) this.undoStack.shift()
    this.redoStack = []
  }

  async undoLastAction(): Promise<void> {
    await this.replay(this.undoStack, this.redoStack, 'undo')
  }

  async redoLastAction(): Promise<void> {
    await this.replay(this.redoStack, this.undoStack, 'redo')
  }

  /**
   * Run the top entry of `from` and move it to `to`, saying what changed. It
   * used to do nothing and say nothing on an empty stack, and a failed write
   * lost the entry to an unhandled rejection; now the entry stays where it was.
   */
  private async replay(from: UndoEntry[], to: UndoEntry[], step: 'undo' | 'redo'): Promise<void> {
    const entry = from.pop()
    if (!entry) {
      this.showNotice(step === 'undo' ? 'Nothing to undo.' : 'Nothing to redo.')
      return
    }
    try {
      await entry[step]()
    } catch (e) {
      console.error('[PM]', e)
      from.push(entry)
      this.showNotice(`Could not ${step}: the case may have changed or been removed.`)
      return
    }
    to.push(entry)
    const what = entry.label ?? 'the last Gantt date change'
    this.showNotice(step === 'undo' ? `Reverted ${what}.` : `Re-applied ${what}.`)
  }

  async onload(): Promise<void> {
    await this.loadSettings()
    this.store = new ProjectStore(this.app, () => this.settings)
    this.store.registerCacheInvalidation(this)
    this.notifier = new Notifier(this)
    this.router = new PMViewRouter(this)

    this.registerView(PM_PROJECT_VIEW_TYPE, (leaf) => new ProjectView(leaf, this))
    this.registerView(PM_DASHBOARD_VIEW_TYPE, (leaf) => new DashboardView(leaf, this))
    this.registerView(CASEFILE_TASK_DETAIL_VIEW_TYPE, (leaf) => new TaskDetailView(leaf, this))
    this.registerView(CASEFILE_TIMELINE_VIEW_TYPE, (leaf) => new TimelineView(leaf, this))
    this.registerView(PHISH_VIEW_TYPE, (leaf) => new PhishAnalysisView(leaf, this))
    if (__STYLEGUIDE__) registerStyleguide(this)

    this.app.workspace.onLayoutReady(
      safeAsync(async () => {
        await migrateProjects(this)
        await this.cleanupStaleProjectFilters()
      })
    )

    this.addRibbonIcon('chart-gantt', 'Open boards pane', async () => {
      await this.router.openDashboard()
    })

    // The handover is the one thing that has to be reachable from any screen at
    // the end of a shift — a palette command nobody knew the name of was not.
    this.addRibbonIcon('fish', 'Analyse a phishing email', () => {
      openPhishAnalysis(this)
    })

    this.addRibbonIcon('clipboard-list', 'Shift handover', () => {
      openHandoverModal(this)
    })

    this.addCommand({
      id: 'open-projects',
      name: 'Open boards pane',
      callback: () => {
        void this.router.openDashboard()
      }
    })

    this.addCommand({
      id: 'open-case',
      name: 'Open case',
      callback: () => {
        void this.openCaseSwitcher()
      }
    })

    this.addCommand({
      id: 'new-project',
      name: 'Create new board',
      callback: () => {
        openProjectModal(this, {
          onSave: async (project) => {
            await this.router.openProjectByPath(project.filePath)
          }
        })
      }
    })

    this.addCommand({
      id: 'new-task',
      name: 'Create new task',
      callback: () => {
        void this.pickProjectThenCreateTask(null)
      }
    })

    this.addCommand({
      id: 'new-subtask',
      name: 'Create new subtask',
      callback: () => {
        void this.pickProjectThenCreateTask('pick-parent')
      }
    })

    this.addCommand({
      id: 'switch-board',
      name: 'Switch board',
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(ProjectView)
        if (!view) return false
        if (!checking) void view.showBoardMenu()
        return true
      }
    })

    this.addCommand({
      id: 'tag-alert-kinds',
      name: 'Tag alert kinds on this board',
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(ProjectView)
        if (!view) return false
        if (!checking) void this.tagAlertKinds(view.projectRef())
        return true
      }
    })

    this.addCommand({
      id: 'group-board-by',
      name: 'Group board by…',
      // Swimlanes used to cost every board a permanent "Lanes: None" row. This
      // is the way in; the board shows a chip with a Clear once one is active.
      checkCallback: (checking) => {
        const board = this.app.workspace.getActiveViewOfType(ProjectView)?.kanban()
        if (!board) return false
        if (!checking) void board.pickLaneGroup()
        return true
      }
    })

    // Ids kept so an assigned hotkey survives the rename. Only Gantt date drags
    // feed this stack, so "last action" claimed more than it undid: after a
    // kanban mis-drop it reverted an older Gantt drag, maybe on another board.
    this.addCommand({
      id: 'undo-last-action',
      name: 'Undo last gantt date change',
      checkCallback: (checking) => {
        if (!this.undoStack.length) return false
        if (!checking) void this.undoLastAction()
        return true
      }
    })

    this.addCommand({
      id: 'redo-last-action',
      name: 'Redo last gantt date change',
      checkCallback: (checking) => {
        if (!this.redoStack.length) return false
        if (!checking) void this.redoLastAction()
        return true
      }
    })

    this.addCommand({
      id: 'import-notes-as-tasks',
      name: 'Import notes as tasks',
      callback: () => {
        void this.importNotes()
      }
    })

    this.addCommand({
      id: 'strip-board-backlinks',
      name: 'Remove board backlinks from task notes',
      callback: () => {
        void this.stripBoardBacklinks()
      }
    })

    this.addCommand({
      id: 'migrate-to-cases-layout',
      name: 'Move boards and tasks into tidy folders',
      callback: () => {
        void this.migrateToCasesLayout()
      }
    })

    this.addCommand({
      id: 'migrate-to-project-folders',
      name: 'Move each board into its own folder',
      callback: () => {
        void this.migrateToProjectFolders()
      }
    })

    this.addCommand({
      id: 'nest-subtask-files',
      name: 'Nest subtasks under their parent tasks',
      callback: () => {
        void this.nestSubtaskFiles()
      }
    })

    this.addCommand({
      id: 'adopt-issue-keys',
      name: 'Adopt issue keys for a board',
      callback: () => {
        void this.adoptIssueKeysFlow()
      }
    })

    this.addCommand({
      id: 'new-incident-from-template',
      name: 'New incident from template',
      callback: () => {
        void this.newIncidentFromTemplate()
      }
    })

    this.addCommand({
      id: 'analyst-toolbox',
      name: 'Analyst toolbox on the selection',
      editorCallback: (editor) => {
        void openToolbox(this, editor)
      }
    })

    this.addCommand({
      // Id kept from 2.30.0 so an assigned hotkey survives the rename.
      id: 'analyse-email-headers',
      name: 'Analyse a phishing email',
      callback: () => {
        openPhishAnalysis(this)
      }
    })

    this.addCommand({
      id: 'generate-shift-handover',
      name: 'Shift handover',
      callback: () => {
        openHandoverModal(this)
      }
    })

    this.addCommand({
      id: 'generate-case-report',
      name: 'Generate case report for the open case',
      // Through safeAsync, so a failure says so instead of vanishing as an unhandled rejection.
      callback: safeAsync(() => this.generateCaseReportForActiveFile())
    })

    this.addCommand({
      id: 'new-case-from-alert',
      name: 'Create case from pasted alert',
      checkCallback: (checking: boolean) => {
        const project = this.activeProjectViewProject()
        if (!project) return false
        if (checking) return true
        new AlertIntakeModal(this.app, this, project, async () => {
          await this.router.openProjectByPath(project.filePath)
        }).open()
        return true
      }
    })

    this.addCommand({
      id: 'create-task-from-selection',
      name: 'Create task from selection',
      editorCheckCallback: (checking, editor) => {
        const selection = editor.getSelection().trim()
        if (!selection) return false
        if (checking) return true
        void this.createTaskFromText(selection)
        return true
      }
    })

    this.registerEvent(
      this.app.workspace.on('editor-menu', (menu, editor) => {
        const selection = editor.getSelection().trim()
        if (!selection) return
        menu.addItem((item) =>
          item
            .setTitle('Create task from selection')
            .setIcon('list-plus')
            .onClick(() => void this.createTaskFromText(selection))
        )
        menu.addItem((item) =>
          item
            .setTitle('Analyst toolbox')
            .setIcon('wand-sparkles')
            .onClick(() => void openToolbox(this, editor))
        )
      })
    )

    this.addCommand({
      id: 'open-current-as-project',
      name: 'Open current file as a board',
      checkCallback: (checking: boolean) => {
        const md = this.app.workspace.getActiveViewOfType(MarkdownView)
        const file = md?.file
        if (!file) return false
        const cache = this.app.metadataCache.getFileCache(file)
        if (cache?.frontmatter?.['pm-project'] !== true) return false
        if (checking) return true
        void md.leaf.setViewState({ type: PM_PROJECT_VIEW_TYPE, state: { filePath: file.path } })
        return true
      }
    })

    // A board note renamed or moved outside Responder (the file explorer, a
    // folder drag, Sync): its filters, collapse state and recent entries
    // follow it, and an open view of it is pointed at the new path, keeping
    // its mode. Obsidian fires this for every note inside a moved folder.
    // The plugin's own moves are skipped: they re-key when they finish.
    this.registerEvent(
      this.app.vault.on(
        'rename',
        safeAsync(async (file, oldPath) => {
          if (this.ownMoves > 0 || !(file instanceof TFile)) return
          if (await this.rekeyProjectPath(oldPath, file.path)) await this.saveSettings()
        })
      )
    )

    this.applyMotionPreference()
    this.addSettingTab(new PMSettingTab(this.app, this))
    this.notifier.start()
    // One plugin-level 30s tick for every SLA chip, wherever it was rendered
    // (board, table, modal, panel). Was per ProjectView, so a chip in a modal
    // opened with no board open never ticked (PS-08).
    const slaTickId = window.setInterval(() => tickAllSlaChips(), 30_000)
    this.registerInterval(slaTickId)
  }

  onunload(): void {
    this.notifier.stop()
  }

  /** Movement effects are CSS-gated on this body class so modals/popovers inherit it too. */
  applyMotionPreference(): void {
    activeDocument.body.classList.toggle('gs-reduce-motion', this.settings.reduceAnimations)
  }

  async loadSettings(): Promise<void> {
    const saved = (await this.loadData()) as Partial<PMSettings> | null
    // Every default is a copy: the settings screens edit these lists in place,
    // and editing DEFAULT_SETTINGS itself changed what "the defaults" meant.
    const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T
    this.settings = Object.assign(clone(DEFAULT_SETTINGS), saved ?? {})
    // Trust boundary: a hand-edited data.json, or a drag dropped on the wrong
    // list, can leave a null or a stray value in a palette, and every loop
    // below and every render reads `.id` — one null kept the plugin from
    // loading. Keep entries with a string id; an empty list gets the
    // defaults. Colours reach CSS `background`, where url() fetches, so
    // anything but a plain colour becomes the neutral grey.
    const palette = <T extends { id: string; color: string }>(v: unknown, defaults: T[]): T[] => {
      const kept = Array.isArray(v)
        ? v.filter((e): e is T => typeof (e as { id?: unknown } | null)?.id === 'string')
        : []
      const list = kept.length ? kept : clone(defaults)
      for (const e of list) e.color = safeColor(e.color, '#8a94a0')
      return list
    }
    this.settings.statuses = palette(saved?.statuses, DEFAULT_SETTINGS.statuses)
    this.settings.priorities = palette(saved?.priorities, DEFAULT_SETTINGS.priorities)
    this.settings.issueTypes = palette(saved?.issueTypes, DEFAULT_SETTINGS.issueTypes)
    this.settings.severities = palette(saved?.severities, DEFAULT_SETTINGS.severities)
    this.settings.verdicts = palette(saved?.verdicts, DEFAULT_SETTINGS.verdicts)
    // Retired verdicts: an older running build can re-save a stale data.json
    // after an upgrade edits it, resurrecting removed entries — prune on load.
    this.settings.verdicts = this.settings.verdicts.filter((v) => v.id !== 'pending' && v.id !== 'duplicate')
    if (!this.settings.verdicts.length) this.settings.verdicts = clone(DEFAULT_SETTINGS.verdicts)
    // Empty is a real choice for these two (every target cleared = no clocks;
    // every template deleted), so only a missing or malformed value gets the
    // defaults. Re-seeding `{}` brought back targets the analyst had removed,
    // and the breach log then recorded misses against them.
    const sla: unknown = saved?.slaPolicies
    if (!sla || typeof sla !== 'object' || Array.isArray(sla)) {
      this.settings.slaPolicies = clone(DEFAULT_SETTINGS.slaPolicies)
    }
    if (!Array.isArray(saved?.incidentTemplates)) {
      this.settings.incidentTemplates = clone(DEFAULT_SETTINGS.incidentTemplates)
    }
    // Keys saved by builds before 2.21 move to device-local storage and are
    // blanked in data.json (ST-5); an existing device-local key is never
    // overwritten by a stale data.json copy.
    let movedKeys = false
    for (const [name, field] of Object.entries(SECRET_FIELDS) as [SecretName, (typeof SECRET_FIELDS)[SecretName]][]) {
      const inData = this.settings[field]
      if (!inData) continue
      if (!this.getSecret(name)) this.setSecret(name, inData)
      this.settings[field] = ''
      movedKeys = true
    }
    if (movedKeys) await this.saveSettings()
    if (!this.settings.projectFilters) this.settings.projectFilters = {}
    if (!this.settings.collapsedTasks) this.settings.collapsedTasks = {}
    if (!this.settings.collapsedKanbanColumns) this.settings.collapsedKanbanColumns = {}
    // Trust boundary: a hand-edited data.json can hand us a string, a null, or
    // numbers inside the list. Filtering to strings (not just checking the
    // container) matters — a non-string element throws out of assetRule inside
    // renderRows and takes the whole Indicators section down.
    // Same trust boundary as ownedAssets: a hand-edited catalog must not throw
    // out of categoryTerms inside every card render, nor its colour fetch.
    this.settings.alertCategories = normalizeAlertCategories(
      (saved as { alertCategories?: unknown } | null)?.alertCategories
    )
    for (const c of this.settings.alertCategories) c.color = safeColor(c.color, '#8a94a0')
    this.settings.ownedAssets = Array.isArray(this.settings.ownedAssets)
      ? this.settings.ownedAssets.filter((v): v is string => typeof v === 'string')
      : []
    // A data.json written by older versions lacks the new filter arrays.
    for (const entry of Object.values(this.settings.projectFilters)) {
      entry.filter.severities ??= []
      entry.filter.verdicts ??= []
    }

    let migrated = false
    for (const s of this.settings.statuses) {
      if (s.complete === undefined) {
        s.complete = s.id === 'done' || s.id === 'cancelled'
        migrated = true
      }
    }

    // 2.26: the shipped default set became To Do / In Progress / User Response /
    // Done. INSERT-ONLY — nothing is removed from a saved list, so a status the
    // analyst edited or kept on purpose survives and no task is ever left on an
    // id the list no longer defines. One-shot, keyed off the SAVED file: the
    // merged `this.settings` carries DEFAULT_SETTINGS' `true` and would skip
    // every existing vault, and re-running it would resurrect a User Response
    // the analyst deleted (the retired-verdicts scar above). Runs AFTER the
    // `complete` backfill (it inserts before the first terminal entry) and
    // BEFORE the ganttHideDone seed, so a seeded filter includes the new status
    // instead of hiding every case parked in it.
    if (saved && !saved.statusDefaultsUpgraded) {
      const upgraded = withUserResponse(this.settings.statuses)
      if (upgraded) {
        this.settings.statuses = upgraded
        new Notice(
          'Responder: added a User Response status, between In Progress and Done. ' +
            'Nothing was removed. Settings → Statuses to rename, reorder or delete it.',
          8000
        )
      }
      this.settings.statusDefaultsUpgraded = true
      migrated = true
    }

    // ganttHideDone was a global gantt toggle; replaced by per-project filter.statuses
    // excluding terminal statuses. Seed projects whose filter has no status selection yet.
    const legacy = (saved ?? {}) as { ganttHideDone?: boolean }
    if (legacy.ganttHideDone === true) {
      const nonTerminal = this.settings.statuses.filter((s) => !s.complete).map((s) => s.id)
      for (const entry of Object.values(this.settings.projectFilters)) {
        if (entry.filter.statuses.length === 0) {
          entry.filter.statuses = nonTerminal
        }
      }
      migrated = true
    }

    if (migrated) await this.saveSettings()
  }

  async cleanupStaleProjectFilters(): Promise<void> {
    let dirty = false
    const prune = <T>(record: Record<string, T>): Record<string, T> => {
      const kept: Record<string, T> = {}
      for (const [path, entry] of Object.entries(record)) {
        if (this.app.vault.getAbstractFileByPath(path)) {
          kept[path] = entry
        } else {
          dirty = true
        }
      }
      return kept
    }
    this.settings.projectFilters = prune(this.settings.projectFilters)
    this.settings.collapsedTasks = prune(this.settings.collapsedTasks)
    this.settings.collapsedKanbanColumns = prune(this.settings.collapsedKanbanColumns)
    if (dirty) await this.saveSettings()
  }

  /**
   * Overlay the persisted collapsed-task state onto a freshly loaded project.
   * Projects with no record yet keep whatever legacy frontmatter said.
   */
  applyCollapsedState(project: Project): void {
    const ids = this.settings.collapsedTasks[project.filePath]
    if (!ids) return
    const set = new Set(ids)
    for (const { task } of flattenTasks(project.tasks)) {
      task.collapsed = set.has(task.id)
    }
  }

  /** Persist the project's current collapsed flags. Call after toggling task.collapsed. */
  async persistCollapsedState(project: Project): Promise<void> {
    this.settings.collapsedTasks[project.filePath] = flattenTasks(project.tasks)
      .filter((f) => f.task.collapsed)
      .map((f) => f.task.id)
    await this.saveSettings()
  }

  /**
   * Flip a task's collapsed flag and persist. Resolves the task by id against
   * the live tree so it works even when a view renders filtered clones.
   */
  async toggleTaskCollapsed(project: Project, taskId: string): Promise<void> {
    const task = findTask(project.tasks, taskId)
    if (!task) return
    task.collapsed = !task.collapsed
    await this.persistCollapsedState(project)
  }

  isKanbanColumnCollapsed(project: Project, statusId: string): boolean {
    return (this.settings.collapsedKanbanColumns[project.filePath] ?? []).includes(statusId)
  }

  /** Flip a kanban column's collapsed flag and persist. Mirrors toggleTaskCollapsed. */
  async toggleKanbanColumnCollapsed(project: Project, statusId: string): Promise<void> {
    const current = this.settings.collapsedKanbanColumns[project.filePath] ?? []
    this.settings.collapsedKanbanColumns[project.filePath] = current.includes(statusId)
      ? current.filter((id) => id !== statusId)
      : [...current, statusId]
    await this.saveSettings()
  }

  async saveSettings(): Promise<void> {
    await this.saveData(this.settings)
  }

  /**
   * Provider API keys live in device-local storage, never in data.json —
   * data.json is exactly the file Sync, iCloud and git-committed vaults
   * replicate (ST-5). Keys typed into an older build are migrated on load.
   */
  getSecret(name: SecretName): string {
    const v: unknown = this.app.loadLocalStorage(`casefile:secret:${name}`)
    return typeof v === 'string' ? v : ''
  }

  setSecret(name: SecretName, value: string): void {
    this.app.saveLocalStorage(`casefile:secret:${name}`, value.trim() || null)
  }

  reputationKeys(): { virustotal?: string; abuseipdb?: string; abusech?: string } {
    return {
      virustotal: this.getSecret('virustotal'),
      abuseipdb: this.getSecret('abuseipdb'),
      abusech: this.getSecret('abusech')
    }
  }

  /**
   * Put a kind on every incident that has none, from its own title.
   *
   * The suggestion is DERIVED, so nothing is written until the analyst has read
   * what would change and why: the confirm lists each case with the exact word
   * that matched. Cases whose title names no kind are counted and skipped, not
   * guessed at, and a case that already carries a kind is never overwritten.
   * The tag is an ordinary tag, so this is reversible by removing it.
   */
  private async tagAlertKinds(project: Project | null): Promise<void> {
    if (!project) return
    const cats = this.settings.alertCategories
    const rows: { id: string; line: string; tag: string }[] = []
    let skipped = 0
    for (const { task } of flattenTasks(project.tasks)) {
      if (task.issueType !== 'incident') continue
      if (categoryForTags(task.tags, cats)) continue
      const hit = suggestCategory(task.title, cats)
      if (!hit) {
        skipped++
        continue
      }
      rows.push({
        id: task.id,
        tag: hit.id,
        line: `${task.key || task.title} → ${hit.label} (matched "${hit.matched}")`
      })
    }
    if (!rows.length) {
      this.showNotice(
        skipped
          ? `Nothing to tag — ${skipped} case(s) have titles that name no kind. Tag those by hand.`
          : 'Nothing to tag — every incident already has a kind.'
      )
      return
    }
    const preview = rows
      .slice(0, 12)
      .map((r) => `• ${r.line}`)
      .join('\n')
    const more = rows.length > 12 ? `\n…and ${rows.length - 12} more` : ''
    const tail = skipped ? `\n\n${skipped} case(s) name no kind and will be left alone.` : ''
    const ok = await confirmDialog(
      this.app,
      `Add a kind tag to ${rows.length} case(s)?\n\n${preview}${more}${tail}`,
      'Tag them'
    )
    if (!ok) return
    const byId = new Map(rows.map((r) => [r.id, r.tag]))
    await this.store.updateTasks(project, [...byId.keys()], (task) => {
      const tag = byId.get(task.id)
      return tag ? { tags: [...task.tags, tag] } : null
    })
    // The glyph reads the tag at render time, so the board has to be told.
    this.refreshProjectViews()
    this.showNotice(`Tagged ${rows.length} case(s)`)
  }

  showNotice(msg: string, duration = 3000): void {
    new Notice(msg, duration)
  }

  /** Re-render every open project view, e.g. after a settings change affects rendering. */
  refreshProjectViews(): void {
    for (const leaf of this.app.workspace.getLeavesOfType(PM_PROJECT_VIEW_TYPE)) {
      if (leaf.view instanceof ProjectView) void leaf.view.refreshProject()
    }
  }

  /** Reveal the right-leaf case timeline for a task, reusing its leaf when one is open (openTaskDetailPanel idiom). */
  openCaseTimeline(project: Project, task: Task): void {
    void (async () => {
      const leaf =
        this.app.workspace.getLeavesOfType(CASEFILE_TIMELINE_VIEW_TYPE)[0] ?? this.app.workspace.getRightLeaf(false)
      if (!leaf) return
      await leaf.setViewState({
        type: CASEFILE_TIMELINE_VIEW_TYPE,
        active: true,
        state: { projectPath: project.filePath, taskId: task.id }
      })
      await this.app.workspace.revealLeaf(leaf)
    })()
  }

  /** Global case switcher over every task (keys shown when present); empty query lists recent cases. */
  private async openCaseSwitcher(): Promise<void> {
    const projects = await this.store.loadAllProjects(this.settings.projectsFolder)
    const hasTasks = projects.some((p) => p.tasks.length > 0)
    if (!hasTasks) {
      this.showNotice('No cases yet. Create a board and add tasks first.')
      return
    }
    openCasePicker(this, projects)
  }

  /** Show project picker, then open TaskModal to create a task (optionally pick parent for subtask) */
  private async newIncidentFromTemplate(): Promise<void> {
    const projects = await this.store.loadAllProjects(this.settings.projectsFolder)
    if (!projects.length) {
      this.showNotice('No boards yet. Create a board first.')
      return
    }
    openProjectPicker(this, projects, (project) => {
      const templates = this.settings.incidentTemplates
      if (!templates.length) {
        this.showNotice('No incident templates configured in settings.')
        return
      }
      const menu = new Menu()
      for (const tpl of templates) {
        menu.addItem((item) =>
          item
            .setTitle(tpl.name)
            .setIcon('siren')
            .onClick(() => {
              this.openTaskModalForProject(project, null, {
                ...tpl.taskDefaults,
                tags: [...(tpl.taskDefaults.tags ?? [])],
                // Picking a template from a menu is not a detection (SD-03): no
                // field has been typed yet. The clock falls back to createdAt —
                // the same instant — and the panel and report now say so.
                description: tpl.bodyMarkdown
              })
            })
        )
      }
      menu.showAtPosition({ x: window.innerWidth / 2 - 100, y: window.innerHeight / 3 })
    })
  }

  /**
   * "Open case" for the report command = the active file, matched against the
   * loaded projects' task files. There is no sync marker for task files, so
   * this resolves after load and explains itself when the file is not a case.
   */
  private async generateCaseReportForActiveFile(): Promise<void> {
    const file = this.app.workspace.getActiveFile()
    if (!file) {
      this.showNotice('Open a case file first.')
      return
    }
    const projects = await this.store.loadAllProjects(this.settings.projectsFolder)
    for (const project of projects) {
      const hit = flattenTasks(project.tasks).find((f) => f.task.filePath === file.path)
      if (hit) {
        await generateCaseReport(this, project, hit.task)
        return
      }
    }
    this.showNotice('The active file is not a case file.')
  }

  /**
   * One-time move from the legacy layout (case file + sibling `X_tasks`
   * folder sprawling in the projects folder) into `Cases/` + `Tasks/<case>/`.
   * Uses fileManager.renameFile so every wikilink — including hand-written
   * ones — updates automatically. Path-keyed settings are re-keyed so
   * filters and collapse state survive.
   */
  /**
   * Delete the `Project: [[Board]]` line from every task note that still has
   * one, in one pass, so turning the setting off does not mean waiting for each
   * note to be re-saved.
   *
   * Deliberately a TEXT edit, not a re-serialize: re-saving every note would
   * restamp 140 `updatedAt` values and destroy the Updated column's sort in one
   * batch. Only whole lines matching the generated shape are removed, and a
   * file that has none is left untouched, so the pass is idempotent and never
   * rewrites a note it did not change.
   */
  private async stripBoardBacklinks(): Promise<void> {
    const files = this.app.vault.getMarkdownFiles()
    const targets: TFile[] = []
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file)
      // Task notes only — the marker the hydrator keys on.
      if (!cache?.frontmatter || cache.frontmatter['pm-task'] !== true) continue
      const text = await this.app.vault.cachedRead(file)
      // search, not test: a /g regex's test() resumes at the last match's end,
      // so every note after a hit was checked from part-way in and skipped.
      if (text.search(BOARD_BACKLINK_RE) !== -1) targets.push(file)
    }
    if (!targets.length) {
      this.showNotice('No task notes carry a board backlink line.')
      return
    }
    const ok = await confirmDialog(
      this.app,
      `Remove the "Project: [[…]]" line from ${targets.length} task note(s)?\n\n` +
        'Only that line is removed. Nothing else in the note changes, and no timestamps are restamped. ' +
        "The plugin never used the line — it finds a task's board from its folder.",
      'Remove them'
    )
    if (!ok) return
    let changed = 0
    for (const file of targets) {
      await this.app.vault.process(file, (text) => {
        const next = text.replace(BOARD_BACKLINK_RE, '').replace(/\n{3,}$/, '\n')
        if (next !== text) changed++
        return next
      })
    }
    this.showNotice(`Removed the board backlink from ${changed} note(s)`)
  }

  private async migrateToCasesLayout(): Promise<void> {
    const root = this.settings.projectsFolder
    const projects = await this.store.loadAllProjects(root)
    const legacy = projects.filter((p) => !isCasesLayout(p.filePath) && !isProjectFolderLayout(p.filePath))
    if (!legacy.length) {
      this.showNotice('All boards already use the Cases/Tasks layout.')
      return
    }
    const ok = await confirmDialog(
      this.app,
      `Move ${legacy.length} board file(s) into ${root}/Cases and their task folders into ${root}/Tasks. Links to the moved notes update automatically.`,
      'Move'
    )
    if (!ok) return
    await this.store.ensureFolder(`${root}/Cases`)
    await this.store.ensureFolder(`${root}/Tasks`)

    let moved = 0
    for (const p of legacy) {
      const oldPath = p.filePath
      const oldTaskFolder = taskFolderForProjectPath(oldPath)
      const base = oldPath.slice(oldPath.lastIndexOf('/') + 1)
      const newPath = normalizePath(`${root}/Cases/${base}`)

      const file = this.app.vault.getAbstractFileByPath(oldPath)
      if (!file) continue
      await this.asOwnMove(async () => {
        await this.app.fileManager.renameFile(file, newPath)
        const taskFolder = this.app.vault.getAbstractFileByPath(oldTaskFolder)
        if (taskFolder) {
          await this.app.fileManager.renameFile(taskFolder, normalizePath(`${root}/Tasks/${base.replace(/\.md$/, '')}`))
        }
      })
      await this.rekeyProjectPath(oldPath, newPath)
      moved++
    }
    await this.saveSettings()
    this.showNotice(`Moved ${moved} board(s) into the Cases/Tasks layout.`)
  }

  /**
   * v3 migration: give every board that is not in its own folder yet one, in
   * place. A legacy `<dir>/X.md` becomes `<dir>/X/X.md` and a v2
   * `<root>/Cases/X.md` becomes `<root>/X/X.md`, with its cases, archive and
   * attachments. A board already in its own folder stays where it was filed:
   * this used to move every filed board back to the vault root and clear the
   * default-folder setting, which says where new boards go, not a layout.
   * Cases/ and Tasks/ folders the v2 boards leave empty are removed; anything
   * non-empty, like unrelated notes, is left untouched.
   */
  private async migrateToProjectFolders(): Promise<void> {
    if (!(this.store instanceof ProjectStore)) return
    const store = this.store
    const projects = await store.loadAllProjects(this.settings.projectsFolder)
    const pending = projects.filter((p) => !isProjectFolderLayout(p.filePath))
    if (!pending.length) {
      this.showNotice('Every board already has its own folder.')
      return
    }
    const ok = await confirmDialog(
      this.app,
      `Move ${pending.length} board(s) into their own folders, each where it is filed now (one folder per board, holding its note and its cases). Links to the moved notes update automatically.`,
      'Move'
    )
    if (!ok) return

    let boards = 0
    let files = 0
    const occupied: string[] = []
    const refused: string[] = []
    const leftovers = new Set<string>()
    for (const p of pending) {
      const name = p.filePath.slice(p.filePath.lastIndexOf('/') + 1).replace(/\.md$/, '')
      // The folder the board is filed in: the note's own for a legacy board,
      // the one holding Cases/ for a v2 board.
      const base = parentFolderOf(p.filePath)
      let result: Awaited<ReturnType<ProjectStore['moveProjectToOwnFolder']>>
      try {
        result = await this.asOwnMove(() => store.moveProjectToOwnFolder(p, base))
      } catch (e) {
        if (!(e instanceof NestedBoardError)) throw e
        refused.push(name)
        continue
      }
      if (result === 'occupied') {
        occupied.push(name)
        continue
      }
      if (!result) continue
      if (isCasesLayout(result.from)) {
        const root = base ? `${base}/` : ''
        leftovers.add(`${root}Cases`).add(`${root}Tasks`)
      }
      await this.rekeyProjectPath(result.from, result.to)
      boards++
      files += result.files
    }

    for (const path of leftovers) {
      const folder = this.app.vault.getAbstractFileByPath(path)
      if (folder instanceof TFolder && folder.children.length === 0) {
        await this.app.fileManager.trashFile(folder)
      }
    }
    await this.saveSettings()

    const parts = [`Moved ${boards} board(s) (${files} file(s)) into their own folders.`]
    if (occupied.length) {
      parts.push(`Skipped ${occupied.length} board(s) whose folder name is already taken: ${occupied.join(', ')}.`)
    }
    if (refused.length) {
      parts.push(`Skipped ${refused.length} board(s) filed inside another board's folder: ${refused.join(', ')}.`)
    }
    new Notice(parts.join('\n'), 10000)
  }

  /**
   * A board note moved: re-key every path-keyed setting (filters, collapse
   * state, recent cases) and re-target open board views, which keep their
   * mode. Callers save settings themselves (batched flows save once at the
   * end); true when a setting changed and needs saving.
   */
  private async rekeyProjectPath(oldPath: string, newPath: string): Promise<boolean> {
    let changed = false
    for (const map of [
      this.settings.projectFilters as Record<string, unknown>,
      this.settings.collapsedTasks as Record<string, unknown>,
      this.settings.collapsedKanbanColumns as Record<string, unknown>
    ]) {
      if (map[oldPath] !== undefined) {
        map[newPath] = map[oldPath]
        Reflect.deleteProperty(map, oldPath)
        changed = true
      }
    }
    for (const r of this.settings.recentCases ?? []) {
      if (r.path === oldPath) {
        r.path = newPath
        changed = true
      }
    }
    for (const leaf of this.app.workspace.getLeavesOfType(PM_PROJECT_VIEW_TYPE)) {
      const view = leaf.view
      if (view instanceof ProjectView && view.filePath === oldPath) {
        await leaf.setViewState({ type: PM_PROJECT_VIEW_TYPE, state: { filePath: newPath, keepView: true } })
      }
    }
    return changed
  }

  /** Run one of the plugin's own board moves; the rename listener leaves its events to it. */
  private async asOwnMove<T>(run: () => Promise<T>): Promise<T> {
    this.ownMoves++
    try {
      return await run()
    } finally {
      this.ownMoves--
    }
  }

  /**
   * Apply a project title change to disk. Under v3 this renames the project's
   * folder and file (link-aware) and re-keys path-keyed settings; older
   * layouts change nothing on disk (the frontmatter title is authoritative).
   * Returns false when the rename was refused (target folder occupied).
   */
  async renameProjectFiles(project: Project, newTitle: string): Promise<boolean> {
    if (!(this.store instanceof ProjectStore)) return true
    const store = this.store
    const moved = await this.asOwnMove(() => store.renameProjectFolder(project, newTitle))
    if (moved === 'occupied') {
      this.showNotice(`A folder named "${projectFileName(newTitle.trim())}" already exists — case not renamed.`)
      return false
    }
    if (moved) {
      await this.rekeyProjectPath(moved.from, moved.to)
      await this.saveSettings()
    }
    return true
  }

  /**
   * Move a board to another folder, keeping everything it owns. One link-aware
   * folder rename carries the board note, its cases, the archive and any
   * attachments; path-keyed settings are re-keyed after it, exactly as a title
   * rename does. Returns false when the target is occupied.
   */
  async moveProjectToFolder(project: Project, base: string): Promise<boolean> {
    if (!(this.store instanceof ProjectStore)) return true
    const store = this.store
    let moved: Awaited<ReturnType<ProjectStore['moveProjectToOwnFolder']>>
    try {
      // Checked before the folder is created: a folder inside a board's own
      // folder, this board's included, is refused, and nothing is left behind.
      store.newProjectFilePath(base, project.title)
      if (base) await store.ensureFolder(base)
      moved = await this.asOwnMove(() => store.moveProjectToOwnFolder(project, base))
    } catch (e) {
      if (!(e instanceof NestedBoardError)) throw e
      this.showNotice(`${e.message} Board not moved.`, 8000)
      return false
    }
    if (moved === 'occupied') {
      this.showNotice(`${base ? `${base}/` : ''}${projectFileName(project.title)} already exists — board not moved.`)
      return false
    }
    if (moved) {
      await this.rekeyProjectPath(moved.from, moved.to)
      await this.saveSettings()
    }
    return true
  }

  /**
   * One-time move of flat subtask files into their parent task's own folder
   * (`Tasks/<case>/<parent-slug>/<sub-slug>.md`). Link-aware renames, safe to
   * re-run; flat vaults keep loading fine without it.
   */
  private async nestSubtaskFiles(): Promise<void> {
    if (!(this.store instanceof ProjectStore)) return
    const store = this.store
    const projects = await store.loadAllProjects(this.settings.projectsFolder)
    let files = 0
    let boards = 0
    for (const p of projects) {
      const moved = await store.nestSubtaskFiles(p)
      if (moved > 0) {
        files += moved
        boards++
      }
    }
    this.showNotice(
      files > 0 ? `Nested ${files} subtask file(s) across ${boards} board(s).` : 'All subtask files already nested.'
    )
  }

  private async adoptIssueKeysFlow(): Promise<void> {
    if (!(this.store instanceof ProjectStore)) return
    const store = this.store
    const projects = await store.loadAllProjects(this.settings.projectsFolder)
    if (!projects.length) {
      this.showNotice('No boards yet.')
      return
    }
    openProjectPicker(this, projects, (project) => {
      void (async () => {
        // Keys are permanent, so the prefix is shown before anything is
        // written. Taking the majority among titles unasked keyed a board
        // whose titles mostly began "APT-29 …" as APT-1, APT-2 …
        const prefix =
          project.keyPrefix ||
          (
            await promptText(
              this.app,
              'Key prefix for this board: letters and digits, starting with a letter. Keys are permanent once given.',
              'SOC',
              { value: inferIssueKeyPrefix(project.tasks) }
            )
          )?.toUpperCase()
        if (!prefix) return
        const ok = await confirmDialog(
          this.app,
          `Adopt issue keys with the prefix ${prefix}. A title that starts "${prefix}-<number>" gives that key to its case, and the prefix is taken off the title, which renames that case's file. Links to those files from notes outside this board's task files will NOT update. Other titles, such as CVE or APT ids, stay as written, and every case without a key gets a fresh ${prefix} key.`,
          'Adopt keys'
        )
        if (!ok) return
        const result = await store.adoptIssueKeys(project, prefix)
        if (!result) {
          this.showNotice('Invalid prefix — keys not adopted.')
          return
        }
        const parts = [`${result.prefix}: adopted ${result.adopted}, assigned ${result.assigned}.`]
        if (result.renamedBasenames.length) {
          const list = result.renamedBasenames.slice(0, 8).join(', ')
          const more = result.renamedBasenames.length > 8 ? ` and ${result.renamedBasenames.length - 8} more` : ''
          parts.push(`Renamed: ${list}${more}. Check hand-written links to these files.`)
        }
        new Notice(parts.join('\n'), 10000)
        this.refreshProjectViews()
      })()
    })
  }

  /** The ACTIVE project view's project (UX-03), else the first open one, for commands scoped to a board. */
  private activeProjectViewProject(): Project | null {
    const active = this.app.workspace.getActiveViewOfType(ProjectView)
    if (active?.project) return active.project
    for (const leaf of this.app.workspace.getLeavesOfType(PM_PROJECT_VIEW_TYPE)) {
      if (leaf.view instanceof ProjectView && leaf.view.project) return leaf.view.project
    }
    return null
  }

  private async pickProjectThenCreateTask(mode: null | 'pick-parent'): Promise<void> {
    const projects = await this.store.loadAllProjects(this.settings.projectsFolder)
    if (!projects.length) {
      this.showNotice('No boards yet. Create a board first.')
      return
    }
    openProjectPicker(this, projects, (project) => {
      if (mode === 'pick-parent') {
        const flat = flattenTasks(project.tasks)
        if (!flat.length) {
          this.showNotice('No tasks on this board. Create a task first.')
          return
        }
        openTaskPicker(
          this,
          flat.map((f) => f.task),
          (parentTask) => {
            this.openTaskModalForProject(project, parentTask.id)
          }
        )
      } else {
        this.openTaskModalForProject(project, null)
      }
    })
  }

  private openTaskModalForProject(project: Project, parentId: string | null, defaults?: Partial<Task>): void {
    openTaskModal(this, project, {
      parentId,
      defaults,
      onSave: async () => {
        await this.store.saveProject(project)
        await this.router.openProjectByPath(project.filePath)
      }
    })
  }

  /** Open the task modal pre-filled from selected text, targeting a chosen project. */
  private async createTaskFromText(text: string): Promise<void> {
    const trimmed = text.trim()
    if (!trimmed) return

    const newlineIdx = trimmed.indexOf('\n')
    const defaults: Partial<Task> =
      newlineIdx === -1
        ? { title: trimmed }
        : { title: trimmed.slice(0, newlineIdx).trim(), description: trimmed.slice(newlineIdx + 1).trim() }

    const projects = await this.store.loadAllProjects(this.settings.projectsFolder)
    if (!projects.length) {
      this.showNotice('No boards yet. Create a board first.')
      return
    }
    if (projects.length === 1) {
      this.openTaskModalForProject(projects[0], null, defaults)
      return
    }
    openProjectPicker(this, projects, (project) => {
      this.openTaskModalForProject(project, null, defaults)
    })
  }

  private async importNotes(): Promise<void> {
    // The board in focus, as alert intake picks it (UX-03). The first open tab
    // was taken before, and a Move import filed notes in another board.
    const activeProject = this.activeProjectViewProject()
    if (activeProject) {
      openImportModal(this, activeProject, async () => {
        await this.router.openProjectByPath(activeProject.filePath)
      })
      return
    }

    const projects = await this.store.loadAllProjects(this.settings.projectsFolder)
    if (!projects.length) {
      this.showNotice('No boards yet. Create a board first.')
      return
    }

    openProjectPicker(this, projects, (project) => {
      const onImportComplete = async () => {
        await this.router.openProjectByPath(project.filePath)
      }
      openImportModal(this, project, onImportComplete)
    })
  }
}
